### ISSUE TITLE
Better support for SD cards and rooted devices

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-File-Manager#10]

**Comment by doodhout** [comment]
Is this implemented already? I've downloaded version 1.5 through F-Droid but I see no way to access root ('/') or the external SDcard.

**Comment by tibbi** [comment]
yes, go to settings and make sure "Show full path" is checked. Then you can click on top breadcrumbs like "/" and you will get into the root folder. That accessing the root folder and sd card will be changed in the future.

**Comment by doodhout** [comment]
I'm sorry for the confusion, I was wrong when saying I'd installed v1.5. On F-Droid the current latest version is v1.3 which does not include this feature yet, if I'm not mistaken.

Let's hope F-Droid will make haste when building the newest versions of this app.
