### ISSUE TITLE
Failed to create file in /system

### ISSUE THREAD

**Issue by mako2580** [SimpleMobileTools/Simple-File-Manager#100]
Hello,
I have root access and /system is mounted as rw and still I'm unable to create file in /system. Android version is 6.0 Marshmallow.
![bug](https://user-images.githubusercontent.com/2705448/31300039-e2de18be-aaf1-11e7-8711-de78f4e0ece4.png)

**Comment by tibbi** [comment]
ye root functionality is still limited

**Comment by tibbi** [comment]
should be fixed in 3.4.0
