### ISSUE TITLE
Detect path "/Removable/MicroSD"

### ISSUE THREAD

**Issue by RyDroid** [SimpleMobileTools/Simple-File-Manager#103]
Hi.

I use version 2.4.0 (from F-Droid) on Asus Tablet (K018) on Android 4.4.2. The path for the (potential) microSD is "/Removable/MicroSD".
The pre-installed file manager detects the microSD and can show its content. However, "this"/"your" application does not.

Regards.

**Comment by tibbi** [comment]
Hm, can you try clearing your app cache by "Clear Data" in the device settings? Maybe the SD card path will be obtained properly. So if you click on the "Internal" at the top left corner, only the "Internal" and "Root" show up?

**Comment by RyDroid** [comment]
I wiped data and cache, it changed nothing. Yes, I have only "Internal" and "Root". Through the root, I can have access to the microSD through the application, so there is no file system right problem.

**Comment by tibbi** [comment]
So apparently only the preinstalled apps can detect SD cards on Android 4.4.x, with other apps its most likely impossible. Ill close it as theres not much to do, or not spending time on.

**Comment by RyDroid** [comment]
At least, SimpleMobileTools "File Manager" (version 3.1.0 of F-Droid) and "Amaze" (version 3.0.1 of F-Droid) - that were not pre-installed - have no problem  to browse "/Removable/MicroSD". SimpleMobileTools "Gallery" (version 3.0.2 of F-Droid) - again not pre-installed - has detected automatically videos on the microSD card. So apparently there is no technical blocker for an application that is not pre-installed.

**Comment by tibbi** [comment]
right, guess I meant modifying those files like deleting or so. Not sure if that will work.
