### ISSUE TITLE
"home folder" has non obvious meaning

### ISSUE THREAD

**Issue by RyDroid** [SimpleMobileTools/Simple-File-Manager#104]
Hi.

I am translating some strings in French. The application uses the concept of "home folder". It is not precise and I don't know how I can translate that ("dossier maison" looks like very strange).
Do you agree to change "home folder" to "default folder" (that is clear and in consequence easy to translate)?

Regards.

**Comment by tibbi** [comment]
It works as a homepage in a browser, meaning it is the initial folder at opening the app. Translate it however you think it's proper for your language. Thanks
