### ISSUE TITLE
Renaming popup not disappearing

### ISSUE THREAD

**Issue by Phoenix1747** [SimpleMobileTools/Simple-File-Manager#125]
So after (apparently) successfully renaming a file the popup window does not disappear again nor does it display a confirmation message. This really confused me for a second until I manually clicked it away and saw that it did indeed rename. Would be nice if the window would at least hide itself again.

**Comment by tibbi** [comment]
Im just working on the file manager, but I cant reproduce it. Does it always happen? Is the file on an SD card, or internal storage?

**Comment by Phoenix1747** [comment]
Really strange, it seems to work again. Nevermind I guess.

The issue occured when changing the file extension of an mp3 file in the internal storage ("Notifications" directory) to ogg.
