### ISSUE TITLE
Possible to add progress bar for file operations ?

### ISSUE THREAD

**Issue by shadowbone94** [SimpleMobileTools/Simple-File-Manager#137]
Is it possible to add a progress bar for operations like 'file copying' and 'moving' ?
I know there is a toast message upon completion of task, but progress of current task can be helpful for files as big as 1 or 2 Gb.

**Comment by ClockGen** [comment]
Indeed a notification is required (even one that just says that there is an operation going on) to avoid killing the app by user or OOM while performing some operations.

**Comment by tibbi** [comment]
it is on the roadmap for multiple apps, will be added someday

**Comment by tibbi** [comment]
an initial version will be added in 3.3.0
