### ISSUE TITLE
Simple-File-Manager crashes when using it as a file picker under ICS (API 16) since version 3

### ISSUE THREAD

**Issue by Olf0** [SimpleMobileTools/Simple-File-Manager#140]
Unfortunately Simple-File-Manager 3.0 crashes when using it as a file picker (i.e. select a file from another app) under Ice Cream Sandwich (API level 16): It crashes in the moment when a file is picked ("Unfortunately Simple File Manager has crashed! [OK]") and no file is returned to the calling app.

All Simple-File-Manager versions before 3.0 (i.e. up to and including v2.6) worked flawlessly.

If logs are deemed helpful, I will capture them and post them here.

**Comment by Olf0** [comment]
Log: [alogcat-mainlog_simplemobiletools.filemanager30_crash-when-picking-file.txt](https://github.com/SimpleMobileTools/Simple-File-Manager/files/1556335/alogcat-mainlog_simplemobiletools.filemanager30_crash-when-picking-file.txt)

**Comment by tibbi** [comment]
thanks, Ill take a look at it someday

**Comment by Olf0** [comment]
Oh, I just realised by looking at the commits, that you @tibbi are basically the sole author of all the SimpleMobileTools apps: Many kudos to you for creating, enhancing and maintaining all these nice, small and deliberately simple apps, as they all of excellent quality, easily installable via F-Droid and definitely are a big enhancement of the app ecosystem, especially on Google-free smartphones.  Although I am primarily just using your file manager, I also tried Draw and your camera app, and their look & feel is really convincing.

WRT the crash of Simple File Manager when picking files under AOSP 4.1.2 (ICS, API level 16): This still happens with version 3.0.1, which was somewhat expected (as the release happened very shortly after this bug report here).
If freshly taken logs with the recent version are helpful for you, please let me know.

Thanks & cheers!

**Comment by tibbi** [comment]
ye I am, so theres a lot of things on the roadmap ;) I havent got here yet, I will someday. API 16 is the minimal required, I dont even have any device for reproduction. Ill probably be able to fix it tho. Thanks

**Comment by Olf0** [comment]
A quick test: Simple Filemanager v3.1.0 (from F-Droid) picked a file for K9-Mail under AOSP 4.1.2 nicely.
Thanks!

Closing this issue (while I would reopen it, if continued testing reveals any further issues WRT file picking).
