### ISSUE TITLE
Unable to install apps

### ISSUE THREAD

**Issue by anthologist** [SimpleMobileTools/Simple-File-Manager#142]
Hi, since the last 2-3 versions I lost the ability to install apks from SimpleFileManager.
I'm on Android 8.1, using the latest Fdroid version, and I already allowed this app the ability to install in the Android settings.
When I try to install an apk, a one-second window appears and than disappears.
Bug?

**Comment by tibbi** [comment]
works fine to me, Ill take a look at it someday

**Comment by AeliusSaionji** [comment]
Came here to say this.

It appears android oreo implemented a new method for sideloading APKs. There is no longer a general toggle in settings: you must grant individual apps permission to sideload apps.

https://developer.android.com/studio/publish/index.html#publishing-unknown

Simple File Manager does not appear in my permission list.

![image](https://user-images.githubusercontent.com/4342746/34646912-2ece2082-f342-11e7-803a-9cfc81157e6b.png)

**Comment by tibbi** [comment]
Ok it will be fixed in version 3.1.0 released hopefully today, thanks

**Comment by anthologist** [comment]
Mine appears in permission list though, I granted it...
Anyway thanks, I'll try v 3.1.0 asap hoping it fixes the problem.

**Comment by AeliusSaionji** [comment]
Confirming 3.1.0 fixes the problem for me.
