### ISSUE TITLE
Unable to resolve 'content://com.simplemobiletools.filemanager.provider' Uris

### ISSUE THREAD

**Issue by billthefarmer** [SimpleMobileTools/Simple-File-Manager#151]
I have had an [issue](https://github.com/billthefarmer/editor/issues/39#issuecomment-354607600) reported on my [Editor](https://github.com/billthefarmer/editor) app by a [user](https://github.com/platypro) using your file manager. The file utilities that I am using to resolve content Uris into 'real' Uris crashes when presented with a 'content://com.simplemobiletools.filemanager.provider' Uri from your file manager. This appears to be because your app does not appear to have a `FileManagerProvider` based on `ContentProvider` as below (from another file manager).
```java
public class FileManagerProvider extends ContentProvider {
    public static final String FILE_PROVIDER_PREFIX = "content://com.veniosg.dir.filemanager";
    public static final String AUTHORITY = "com.veniosg.dir.filemanager";
```
I don't know if this is a feature or a bug, I can work around it, but not resolve the Uri.

**Comment by tibbi** [comment]
You cannot resolve third party uris into real file paths. It is an Android 7 security feature which Im using in previous versions too, nothing to be changed on my side there.

**Comment by billthefarmer** [comment]
I am well aware of the Android 7 security feature. However yours is the first android file manager I have encountered which does not allow it's Uris to be resolved. The behaviour is not consistent, you return standard `content://media` Uris for files not created by the app, but return unresolvable `content://com.simplemobiletools.filemanager.provider` Uris for files created by the app. An android file manager which does not allow it's Uris to be resolved is, IMHO, not a lot of use. You do add a `real_uri` extended data field to the intent, but that again isn't consistent with other file managers.

**Comment by tibbi** [comment]
Try first increasing your minSDK to at least 26 before trying other apps. If you stick to old SDKs, you wont be able to update or publish apps on playstore soon.
