### ISSUE TITLE
left sidebar for favorites and storage devices

### ISSUE THREAD

**Issue by lucamp** [SimpleMobileTools/Simple-File-Manager#155]
Hi,
having a left sidebar that shows by swiping it from left to right would be pretty useful as inside there is space for shortcut like:

_ internal memory
_ sd card
_ favorites 

Thanks for your app
Luca

**Comment by tibbi** [comment]
thats a navigation-drawer like behaviour, I dont really like that.I will think of something once Ill be redesigning it, which wont be anytime soon tho.
