### ISSUE TITLE
language setting is sticky

### ISSUE THREAD

**Issue by olafhering** [SimpleMobileTools/Simple-File-Manager#156]
Installed the app for first time on LineageOS klteduos, from fdroid.
App came up in German. In setting the knob for English disabled localization.
But it will not switch back to German.

**Comment by trubitsyn** [comment]
Version 3.1.0 works fine for me.

**Comment by olafhering** [comment]
I think the bug is that switching does not seem to happen instantly. And double-back does not close the app for real. O have to use the appswitcher and X it out.

If it runs in German toggling the knob switches to English instantly. But it does not switch back.

One has to toggle to localized, then exit, then terminate, then restart.

**Comment by olafhering** [comment]
Build thanks for the knob anyway. Best idea ever.

**Comment by trubitsyn** [comment]
The thanks go to @tibbi. I'm not the author of the app :)
