### ISSUE TITLE
Implement and/or use rename()

### ISSUE THREAD

**Issue by olafhering** [SimpleMobileTools/Simple-File-Manager#157]
I'm surprised the "move $file to ..." seems to actually be a copy operation: the timestamp is lost even on the same filesystem.

It would be nice to use rename(), and fallback to copy&utimes if ECROSSFS is returned.

**Comment by tibbi** [comment]
I used to be using renameTo, but it has many different issues so I went back to copy/delete on Android 7+

**Comment by olafhering** [comment]
It seems the LineageOS built-in file manager does rename(), at least the time stamp is preserved.

**Comment by tibbi** [comment]
the timestamp can be modified in a different way too, the most important benefit of renameTo is that is it instant. Do you have "Keep old last-modified value..." enabled in Simple File Manager settings? It should work on internal storage files. What Android OS version do you have? Thanks

**Comment by olafhering** [comment]
Current LineageOS on klteduos, 7.1.2

**Comment by Ricciolone** [comment]
I have an old Nexus 7 2013 with Android 6.0.1 stock rooted.
I confirmed the option 

> keep old last-modified value at file copy/move/rename

When I copy with Simple-File-Manager from inside to inside (duplicate to another folder) it updates all the timestamps. Even if I set it as root, it updates all timestamps anyway.
The only way I can keep my timestamps was by installing 

> Terminal Emulator for Android

 and writing 
`cp -p source destination`. 
This way, even when copying from an SD OTG, it keeps all timestamps.
Can you solve it? Can you tell me about any file managers who keep the timestamps?

Thanks and congratulations for your apps.

Translated with www.DeepL.com/Translator

**Comment by tibbi** [comment]
I dont really know about any as Im not using them, and it depends on your device and usecase if it works fine.

**Comment by Ricciolone** [comment]
I understand

2018-05-30 22:42 GMT+02:00 Tibor Kaputa <notifications@github.com>:

**Comment by tibbi** [comment]
rename is already used when moving files from internal storage to internal storage
