### ISSUE TITLE
Cannot Add Favorite for Another Directory Right After a Prior Favorite Creation

### ISSUE THREAD

**Issue by thewizardstudio** [SimpleMobileTools/Simple-File-Manager#169]
#### Expected Behavior
The user has the option to Add Favorite whenever they are in a directory which is not already a favorite.

#### Actual Behavior
The user does not have the ability to Add Favorite in a directory right after doing so in a different directory.  The menu says Remove Favorite where it should say Add Favorite.

#### How to Reproduce
1. Launch File Manager 3.2.0 on Android 8.1.0
2. Go to a folder which contains another folder
3. Tap the 3 Vertical Dots in upper right
4. Tap Add to Favorites
5. Tap the other folder in the current directory to enter it
6. Tap the 3 Vertical Dots in upper right

---
    Device: Pixel 2 XL
    OS: Android 8.1.0
    App Version: 3.2.0
---
#### Recording of the Bug
![RemoveNonFavorite.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517166361/vvfx4oblepw2iwc0ogci.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thewizard.studio/cannot-add-favorite-for-another-directory-right-after-a-prior-favorite-creation">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by trubitsyn** [comment]
@tibbi working on it.
