### ISSUE TITLE
Does not offer Firefox for HTML file

### ISSUE THREAD

**Issue by contrapunctus-1** [SimpleMobileTools/Simple-File-Manager#183]
My apologies if this is not a Simple File Manager problem.

Simple FM (v3.2.1 from F-Droid) does not offer Firefox (Nightly, v60.0a1) as an option when trying to open an HTML file. I also tried this with Dir - which exhibited the same behavior - and with Amaze - which didn't (i.e. it offered Firefox as an option).

What SFM does offer, on my device (Moto G 5s Plus, Android v7.1.1) - Book Reader, Amaze Text Editor, Ghost Commander's Text Viewer and Text Editor, SFM's File Editor, HTML Viewer, and Chrome.

**Comment by contrapunctus-1** [comment]
Does seem to be a Firefox problem - https://bugzilla.mozilla.org/show_bug.cgi?id=1406903

**Comment by tibbi** [comment]
I havent checked it yet, but that could be the issue. I have to use content:// uri since Android 7+ for security reasons, the app will crash if I try sharing a file:// file. It could need some mimetype tweak too, not sure now.

**Comment by tibbi** [comment]
yea, that is the issue. Ill leave the issue open, but theres nothing I can do on my side. I could hackfix it for Android 4,5,6, but I dont want to do that. They have to fix it.

**Comment by tibbi** [comment]
it has been closed, guess it works already
