### ISSUE TITLE
Samsung Dex support 

### ISSUE THREAD

**Issue by F3000** [SimpleMobileTools/Simple-File-Manager#188]
Please add support for this. More infos can be found here : 

http://developer.samsung.com/samsung-dex/modify-optimizing

http://developer.samsung.com/samsung-dex/modify-optional

A dex station have a ethernet port . So you can integrate for business users a smb viewer in your app. So we can mount network drives . 

The App should be Build withe API 24 and have to support the Android-N multiwindow view.

**Comment by tibbi** [comment]
moved to https://github.com/SimpleMobileTools/General-Discussion/issues/64
