### ISSUE TITLE
Simple-File-Manager 3.3.{1,2,3} crash, when used as a file picker under AOSP 4.1.2 (API 16)

### ISSUE THREAD

**Issue by Olf0** [SimpleMobileTools/Simple-File-Manager#191]
Unfortunately Simple-File-Manager versions 3.3.1, 3.3.2 and 3.3.3 (installed from F-Droid) crash, when using it as a file picker (i.e. selecting a file for another app) under "Jelly Bean" (v4.1.2, API level 16): It crashes in the moment when a file is picked ("Unfortunately Simple File Manager has crashed! [OK]") and no file is returned to the calling app.

Simple-File-Manager versions 3.3.0, 3.2.1, 3.2.0, 3.1.0 and all versions before 3.0 (i.e. up to and including v2.6) were working flawlessly as a file-picker.

I will try to record a log-file and post it here (this weekend, if time permits).

**Comment by Olf0** [comment]
Mainlog filtered for "simplemobiletools", when trying to use Simple Filemanager versions 3.3.1 and 3.3.2 as a file-picker:
* [alogcat-mainlog_simple-filemanager-3.3.1_filtered-simplemobiletools.txt](https://github.com/SimpleMobileTools/Simple-File-Manager/files/1801112/alogcat-mainlog_simple-filemanager-3.3.1_filtered-simplemobiletools.txt)
* [alogcat-mainlog_simple-filemanager-3.3.2_filtered-simplemobiletools.txt](https://github.com/SimpleMobileTools/Simple-File-Manager/files/1801113/alogcat-mainlog_simple-filemanager-3.3.2_filtered-simplemobiletools.txt)

Unfortunately I forgot to record the eventlog in both cases.  When deemed helpful (@tibbi, please let me know), I can reinstall Simple Filemanager 3.3.2 or 3.3.1 and do that.

**Comment by tibbi** [comment]
this should be enough, I probably see the reason. Ill take a look at it someday, thanks.

**Comment by Olf0** [comment]
Simple-File-Manager 3.4.0 (installed from F-Droid) crashes differently, when using it as a file picker (under AOSP 4.1.2, API level 16): It crashes immediately, when it is selected in the intent dialogue for file picking; i.e. it does not even open, in contrast to Simple-File-Manager versions 3.3.{1,2,3}, which open, but crash in the moment a file is selected.

[Main log]

**Comment by tibbi** [comment]
many things changed since then, reopen this if it still happens with version 5.0.2

**Comment by Olf0** [comment]
Retested with Simple File Manager 4.3.1 from F-Droid, which seems to be the last version supporting API levels 16 to 19 (Android 4.1.0 to 4.4.4):
Behavior unchanged compared to v3.4.0: Simple File Manager crashes in the moment it is called as a file picker from the Android intent chooser.

Logs:
* [alogcat-mainlog_simple-filemanager-4.3.1_filtered-simplemobiletools.txt](https://github.com/SimpleMobileTools/Simple-File-Manager/files/2612723/alogcat-mainlog_simple-filemanager-4.3.1_filtered-simplemobiletools.txt)
* [alogcat-eventlog_simple-filemanager-4.3.1_filtered-simplemobiletools.txt](https://github.com/SimpleMobileTools/Simple-File-Manager/files/2612725/alogcat-eventlog_simple-filemanager-4.3.1_filtered-simplemobiletools.txt)
