### ISSUE TITLE
Can’t open OTG devices 

### ISSUE THREAD

**Issue by F3000** [SimpleMobileTools/Simple-File-Manager#193]
Device : 
Galaxy Tab S2 

OS: 
7.0 

Google Security Patch : 
1.Janunary 2018 

I plug in my OTG Adapter and put in any usb stick. 
I open file manager and select OTG. After that the app crashes directly and I see a pop up with : the app has been crashed. 

I used different sticks and one 2.5” HDD. Always the same . 

Do you have an idea ? 
Can I send logs to you ?

**Comment by tibbi** [comment]
Ive seen some OTG crashes, but couldnt reproduce any. You can send some logs if you have. Thanks

**Comment by F3000** [comment]
In which log level ?

**Comment by tibbi** [comment]
I dont know, whatever you have. You can send the most verbose and Ill see if theres something inside.

**Comment by F3000** [comment]
Ok . I will loook Tomorrow and upload it here

**Comment by F3000** [comment]
ok i have to correct. I Have tedted another time. So when i try to use the OTG Adapter i see the files saved on the stick under "SD-Card" and not under OTG. 

Is that a BUG or a normal android behaiviour ?

**Comment by tibbi** [comment]
OTG can still be glitchy, the handling is still quite new. It isnt a top priority either as not many people use it.

**Comment by tibbi** [comment]
reopen if it is still broken with app version 6.0.1
