### ISSUE TITLE
Unable to send multiple files via Bluetoth in V3.0+

### ISSUE THREAD

**Issue by mtris** [SimpleMobileTools/Simple-File-Manager#198]
Hello:  I have been unable to send multiple files via Bluetooth since apk v3.0.  It will allow me to select the files, select share via Bluetooth, and select the device to send them to.  One the device is selected there is a pop-up message at the bottom of the screen '1400  Files not sent'.  For example:  If I select 5 files to send, the message at the bottom will indicate that One thousand Four hundred files were selected and failed.

I have tried several of the new releases, but encounter the same problem each time.  I have to uninstall the upgrade and remain with v2.6.0 as this version is the most current version that will complete the task.  Please advise, and thank you for your consideration.  Thank you.

Sincerely,

**Comment by tibbi** [comment]
some related thing will be fixed in version 5.0.2, reopen if it is still broken
