### ISSUE TITLE
New Logo Proposal for Simple File Manager

### ISSUE THREAD

**Issue by mdnazmulhasan27771** [SimpleMobileTools/Simple-File-Manager#200]
**Hello,
This my logo design for your project. It's free.I design this logo using adobe illustrator cc 2017. I hope you like this logo**

![logo-01](https://user-images.githubusercontent.com/35112507/37851932-e64caa72-2f0a-11e8-9b67-2a5ddcafe8df.jpg)

**My presentation is preserved below**

![presentation](https://user-images.githubusercontent.com/35112507/37851996-218a7902-2f0b-11e8-9795-59687a75afa5.png)

**All Source File [HERE](https://drive.google.com/open?id=1uihDHGr-elv6oZXJWKmnZqotoYE0JjB6)**

**If you need anything change please contact me** 

**Md Nazmul Hasan**
**Email : mdnazmul.hasan27771@gmail.com**

**Thank You.**

**Comment by tibbi** [comment]
Oh gosh, that is a really complicated one. I dont plan changing it anytime soon, thanks though.

**Comment by mdnazmulhasan27771** [comment]
sorry, I am not gosh I am Md Nazmul Hasan...

**Comment by mdnazmulhasan27771** [comment]
I proposal this logo/icon for future...
