### ISSUE TITLE
Unable to set a song as a ringtone using the "set as" button. Instead, an error message is displayed.

### ISSUE THREAD

**Issue by codaphrenic** [SimpleMobileTools/Simple-File-Manager#201]
#### Expected behavior
I expect that when I click the **set as** button on a song from the options menu, I should be able to set the song as a ringtone,  the same way the application allows for pictures to be set as wallpapers. 

#### Actual behavior

On clicking the **set as** button on a song, there is no visible response. Nothing happens, instead the following pops up:

```
No app for opening this type of file is installed
```

However, setting a picture as a wallpaper is possible.

#### How to reproduce
* download the app from fdroid store
* launch app and allow permissions if prompted
* Open a folder that contains music
* Click and hold the particular song
* Now click on the the three dots at the top right corner of the display, a menu displays
* Click on the **set as** button to see the error message displayed

***

* Device: TECNO-L8Plus 
* Operating system: Android 5.1

* Application: Simple File Manager
* version: 3.3.2

#### Recording Of The Bug

<sub>
The recording below shows it was possible to set a picture as a wallpaper but didn't work with setting a song as a ringtone.
</sub>
<center>
https://youtu.be/W9mZdyc9mAo
</center>
 

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@fego/unable-to-set-a-song-as-a-ringtone-using-the-set-as-button-instead-an-error-message-is-displayed">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by tibbi** [comment]
it is handled by the system, not me
