### ISSUE TITLE
Bug found in simple file manager (when i delete folder error come on the  secreen)

### ISSUE THREAD

**Issue by abdulmalikkhan655** [SimpleMobileTools/Simple-File-Manager#202]
#### Expected behavior

According to my knowledge, when I sort out a folder and delete it, the folder will be deleted And that folder will always remove from my mobile phone forever

#### Actual behavior
As I delay a folder and after deleting it re-closing this application again The folder comes again but does not have a delete 

#### How to reproduce
* [Download](https://play.google.com/store/apps/details?id=com.simplemobiletools.filemanager&hl=en) and install 
*  open and goto sdcard option 
* find the folder you want to delet 
* hold on folder and delete  them 
* after delete the folder restart the application
* you will be seen folder  in your phone 
* note the bug 
* Browser: Simple File Manager version 3.3.2

* Operating system: anroid 4.4.4

* Smart Phone samsung j1 ace

#### Recording Of The Bug
https://youtu.be/knS5oQgcr0g
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@abdulmalikkhan/bug-found-in-simple-file-manager-when-i-delete-folder-error-come-on-the-secreen">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by tibbi** [comment]
sd cards are not supported on Android 4.x, so dont really expect this being fixed
