### ISSUE TITLE
Can't give write access to SD-Card

### ISSUE THREAD

**Issue by realthargor** [SimpleMobileTools/Simple-File-Manager#207]
When trying to delete a folder from the sdcard, a dialog pops up to grant write access.
Selecting the SDCard results in the message: "SDCard and OTG device pathes can't be the same."

Version: File Manager 3.3.2
Device: OnePlus X
Storage:
- Internal
- Micro SDCard

**Comment by tibbi** [comment]
So you had an OTG device plugged in previously and selected some path? Do file operations work on that otg?
