### ISSUE TITLE
Error when trying to delete files

### ISSUE THREAD

**Issue by ghost** [SimpleMobileTools/Simple-File-Manager#209]
Hello i would like to report a problem with the file manager. When I try to delete a file no matter if it is on an SD card or internal memory, it "deletes" it. However, when you exit and enter again the file appears again.

Application provider: F-Droid 1.0
file manager: 3.3.3
Android": 4.4.2 

I would like to express my gratitude for all your work, the world needs more heroes like you. Open source oriented.
Thank you very much!

**Comment by tibbi** [comment]
reopen if it will still be broken with version 4.3.0
