### ISSUE TITLE
Can't copy/move from internal to root

### ISSUE THREAD

**Issue by andreapx** [SimpleMobileTools/Simple-File-Manager#210]
Hi and first of all thanks for this and all the other simple apps!
I'm trying to copy some files from the download folder to USB-OTG,but when, after clicking on "Copy to", I click on "Internal" to change it to root", the list stays empty, it doesn't show any file/folder.
Andrea

Version 3.3.3 on a Moto Z Griffin with Resurrection Remix ROM

**Comment by tibbi** [comment]
should be fixed in 3.4 on rooted devices

**Comment by andreapx** [comment]
Wonderful!!!
Thanks!
