### ISSUE TITLE
Can not rename file music on SdCard. Android 4.4.4

### ISSUE THREAD

**Issue by nissa-sabyan** [SimpleMobileTools/Simple-File-Manager#226]

**Comment by tibbi** [comment]
sd cards arent supported on Android 4.x so dont really expect this being fixed

**Comment by nissa-sabyan** [comment]
Why be like that ,?
Internal is work?

**Comment by tibbi** [comment]
internal works, but google made SD card support pretty much impossible on Android 4.4

**Comment by tibbi** [comment]
ill close this as it wont be fixed
