### ISSUE TITLE
Inverted storage name

### ISSUE THREAD

**Issue by ghost** [SimpleMobileTools/Simple-File-Manager#230]
Hi,

When i choose in rom settings to use my sdcard as default storage, in simple file manage i saw the interne storage rename as sdcard and sdcard rename as interne storage. Is that normal ?

The default stock rom file manage despite of changing the default storage to sd keeps the name and position.

 Below 2 screen shot after switching storage in stock and simple file manager

![](https://i.imgur.com/ZThxb7b.jpg)
![](https://i.imgur.com/ci41TXt.jpg)

**Comment by tibbi** [comment]
What app version and Android OS version do you have? The Android file system is already messed up well enough, setting SD card as the internal storage seems like a terrible idea.

**Comment by AqwelF** [comment]
Sorry forget it : 
Honor 9 stf l09 c432
Android oreo 8.0 under emui 8 (364)
App version 4.0.0

I begin in the android world. No have clue its risky. Thanks for the advice.

**Comment by tibbi** [comment]
should be fixed already
