### ISSUE TITLE
Decompressing .zip files with folders misses a path separator

### ISSUE THREAD

**Issue by ant9000** [SimpleMobileTools/Simple-File-Manager#240]
Decompressing an archive `/sdcard/Download/archive.zip` that contains `folder/example.txt`, one would expect to find  `/sdcard/Download/folder/example.txt` (extract contents in the directory of the zip file) or even better `/sdcard/Download/archive/folder/example.txt` (create a new folder with the zip name, and extract contents there) - instead, I get `/sdcard/Downloadfolder/example.txt`.

I'm using version 4.0.0 from F-Droid.

**Comment by tibbi** [comment]
it will be fixed in 4.3.0
