### ISSUE TITLE
Feature request standard file viewers

### ISSUE THREAD

**Issue by Yanpas** [SimpleMobileTools/Simple-File-Manager#243]
Here is low quality screenshot from filza fm, something similar would be handy for this fm. I can't even view source code files now.
![default](https://user-images.githubusercontent.com/7345761/41587991-35cb59d4-73b9-11e8-8070-baaef13ab48e.jpeg)
Ideas for viewers:
- text editor
- image viewer
- document viewer (pdf etc)
- multimedia viewer
- sqlite3
- archieve preview

**Comment by tibbi** [comment]
an "Open as" menu item will be added in 4.3.0, with that you will be able to open the file as a text file
