### ISSUE TITLE
deleting a file in sdcard

### ISSUE THREAD

**Issue by sultanahamer** [SimpleMobileTools/Simple-File-Manager#245]
I have stopped using simple file manager for below reasons

1. Not able too delete file in sdcard
2. Not able to install apks. Upon click it says app not installed or present. But the same works in other file managers on fdroid
3. I have my own app which opens vcard files but if I open vcard from simple file manager, it doesn't show my app in apps list that support vcard. But with other apps same functionality is working.

**Comment by tibbi** [comment]
What app version and Android OS version do you have? What do you mean by not able to delete SD card files? Do you get some error, or what?

**Comment by sultanahamer** [comment]
Sorry my friend, I was using older version of the app, just updated and to the newer and its working now. My bad.

**Comment by sultanahamer** [comment]
Off all 3 of the above, I see only third one as issue. Will open a new ticket for that.
