### ISSUE TITLE
Not showing all the apps that can open vcard files

### ISSUE THREAD

**Issue by sultanahamer** [SimpleMobileTools/Simple-File-Manager#246]
I have my own app which opens vcard files but if I open vcard from simple file manager, it doesn't show my app in apps list that support vcard. But with other apps same functionality is working.

Android OS: 6.0 AOSP
App version: 4.0.0

Below screenshot shows me opening a vcf file using simple file manager and its not showing my application(import contacts) which can open it in the list.
![screenshot_20180627-101947](https://user-images.githubusercontent.com/11389059/41953811-55e22a30-79f5-11e8-8d5f-78da93e6e59c.png)

Below screenshot shows me opening a vcf file using  stock file manager which shows import contacts in the apps list
![screenshot_20180627-102014](https://user-images.githubusercontent.com/11389059/41953828-746e90ba-79f5-11e8-9b87-8fe1b2ef2c03.png)

**Comment by tibbi** [comment]
can you debug the stock app and check in Logcat what intent does it invoke?

**Comment by sultanahamer** [comment]
@tibbi here is the logcat.

In the below logcat you can find the **media query**

`V MediaProvider: query: uri=content://media/external/file, selection=_data = '/storage/00CD-17EA/Contacts_16-02-18 05-22-17 .vcf'`

then the **action and data url**

`I ActivityManager: START u0 {act=android.intent.action.VIEW dat=file:///storage/00CD-17EA/Contacts_16-02-18 05-22-17 .vcf typ=text/x-vcard cmp=android/com.android.internal.app.ResolverActivity} from uid 10125 on display 0`

then it **resolved** to my app's activity and finally others

`getActivityInfo ComponentInfo{opencontacts.open.com.opencontacts/opencontacts.open.com.opencontacts.activities.ImportVcardActivity}: Activity{b23eb11 opencontacts.open.com.opencontacts/.activities.ImportVcardActivity}`

Below is **complete** log


`09-19 14:15:10.644 18223 18223 D gengqiang: onListItemClick->open file
09-19 14:15:10.648 17879 18040 V MediaProvider: query: uri=content://media/external/file, selection=_data = '/storage/00CD-17EA/Contacts_16-02-18 05-22-17 .vcf'
09-19 14:15:10.681  1399  2367 I ActivityManager: START u0 {act=android.intent.action.VIEW dat=file:///storage/00CD-17EA/Contacts_16-02-18 05-22-17 .vcf typ=text/x-vcard cmp=android/com.android.internal.app.ResolverActivity} from uid 10125 on display 0
09-19 14:15:10.681  1399  2367 D ActivityManager: DEBUG_POWER_HINT start activityh
09-19 14:15:10.692  1399  2367 V WindowManager: Pausing WindowToken AppWindowToken{269883b token=Token{ccb8eca ActivityRecord{d46a35 u0 com.fihtdc.filemanager/.FileManagerMain t1075}}}
09-19 14:15:10.697  1399  2367 D WindowManager: Input focus has changed to null
09-19 14:15:10.697  1399  2367 D ActivityManager: startActivityUncheckedLocked return : 0
09-19 14:15:10.707  1081  1122 D phoneserver: rsrp[0]=-255,rscp[0]=13,rxlev[0]=99 ind_str=
09-19 14:15:10.707  1081  1122 D phoneserver: +CESQ: 99,99,13,255,255,-255
09-19 14:15:10.707  1081  1122 D phoneserver: rsrp[1]=-255,rscp[1]=255,rxlev[1]=29 ind_str=
09-19 14:15:10.707  1081  1122 D phoneserver: +CESQ: 29,5,255,255,255,-255
09-19 14:15:10.712 18223 18223 D Aaron   : recent update issuccess 1
09-19 14:15:10.718 18223 18280 E sdkstat : sdkstat page time = file_list_all_view; time = 15397
09-19 14:15:10.721  1399  1784 V PackageManager: getPackageGidsandroid: Package{6998c48 android}
09-19 14:15:10.722  1399  1693 V PackageManager: getPackageInfo com.fihtdc.filemanager: Package{911bf0f com.fihtdc.filemanager}
09-19 14:15:10.737  1399  1784 I ActivityManager: Start proc 18339:system:ui/1000 for activity android/com.android.internal.app.ResolverActivity
09-19 14:15:10.737  1399  1784 V WindowManager: Resuming WindowToken AppWindowToken{269883b token=Token{ccb8eca ActivityRecord{d46a35 u0 com.fihtdc.filemanager/.FileManagerMain t1075}}}
09-19 14:15:10.764  1399  2400 V ActivityManagerServiceMU: generateApplicationProvidersLocked, app.info.uid = 1000
09-19 14:15:10.768  1399  2389 V PackageManager: getPackageInfo android: Package{6998c48 android}
09-19 14:15:10.777  1399  2396 V PackageManager: getPackageInfo system:ui: null
09-19 14:15:10.777  2317 27587 D FileOperator: Mode change to WRITE_MODE!
09-19 14:15:10.778  2317 27587 D FileOperator: initiateWrittenFile()
09-19 14:15:10.795  1399  2389 V PackageManager: getPackageInfo system: null
09-19 14:15:10.800  1399  2400 V PackageManager: getPackageInfo android: Package{6998c48 android}
09-19 14:15:10.802  1399  1410 V PackageManager: getPackageInfo android: Package{6998c48 android}
09-19 14:15:10.804  1399  2382 V PackageManager: getPackageInfo system: null
09-19 14:15:10.804  1399  2396 V PackageManager: getPackageInfo system: null
09-19 14:15:10.910  1399  2400 V PackageManager: getActivityInfo ComponentInfo{opencontacts.open.com.opencontacts/opencontacts.open.com.opencontacts.activities.ImportVcardActivity}: Activity{b23eb11 opencontacts.open.com.opencontacts/.activities.ImportVcardActivity}
09-19 14:15:10.916  1399  1799 V PackageManager: getPackageInfo system: null
09-19 14:15:10.916  1399  2434 V PackageManager: getPackageInfo opencontacts.open.com.opencontacts: Package{31d8b4 opencontacts.open.com.opencontacts}
09-19 14:15:10.917  1399  1856 V PackageManager: getPackageInfo android: Package{6998c48 android}
09-19 14:15:10.920  1399  1409 V PackageManager: getPackageInfo system: null
09-19 14:15:10.920  1399  2367 V PackageManager: getPackageInfo system: null
09-19 14:15:10.929  1399  1756 V PackageManager: getPackageInfo system: null
09-19 14:15:10.929  1399  2410 V PackageManager: getPackageInfo com.android.contacts: Package{3938939 com.android.contacts}
09-19 14:15:10.930  1399  1693 V PackageManager: getPackageInfo android: Package{6998c48 android}
09-19 14:15:10.931  1399  1784 V PackageManager: getPackageInfo system: null
09-19 14:15:10.932  1399  1873 V PackageManager: getPackageInfo system: null
09-19 14:15:10.938  1399  2400 V PackageManager: getPackageInfo system: null
09-19 14:15:10.938  1399  1410 V PackageManager: getPackageInfo com.simplemobiletools.filemanager: Package{f2c6674 com.simplemobiletools.filemanager}
09-19 14:15:10.939  1399  2382 V PackageManager: getPackageInfo android: Package{6998c48 android}
09-19 14:15:10.940  1399  2396 V PackageManager: getPackageInfo system: null
09-19 14:15:10.941  1399  1799 V PackageManager: getPackageInfo system: null
09-19 14:15:10.950 18339 18339 D AccessibilityManager: getInstance() new sInstance = android.view.accessibility.AccessibilityManager@e499bf0, context = com.android.internal.app.ResolverActivity@99977a2, userId = -2
09-19 14:15:10.978  1399  2367 V PackageManager: getApplicationInfo opencontacts.open.com.opencontacts: Package{31d8b4 opencontacts.open.com.opencontacts}
09-19 14:15:10.986  1399  1784 V WindowManager: addWindow: New client android.os.BinderProxy@d158cad: window=Window{dd7cbe2 u0 android/com.android.internal.app.ResolverActivity} Callers=com.android.server.wm.Session.addToDisplay:168 android.view.IWindowSession$Stub.onTransact:124 com.android.server.wm.Session.onTransact:130 android.os.Binder.execTransact:453 <bottom of call stack>
09-19 14:15:11.000  1399  2389 V PackageManager: getApplicationInfo com.android.contacts: Package{3938939 com.android.contacts}
09-19 14:15:11.005  1399  2400 D WindowManager: Input focus has changed to Window{dd7cbe2 u0 android/com.android.internal.app.ResolverActivity}
09-19 14:15:11.011  1399  2396 V PackageManager: getApplicationInfo com.simplemobiletools.filemanager: Package{f2c6674 com.simplemobiletools.filemanager}
09-19 14:15:11.025  1399  1799 V PackageManager: getApplicationInfo com.android.contacts: Package{3938939 com.android.contacts}
09-19 14:15:11.029  1399  2434 V PackageManager: getApplicationInfo com.simplemobiletools.filemanager: Package{f2c6674 com.simplemobiletools.filemanager}
09-19 14:15:11.031  1399  1856 V PackageManager: getApplicationInfo com.android.contacts: Package{3938939 com.android.contacts}
09-19 14:15:11.032  1399  1409 V PackageManager: getApplicationInfo com.simplemobiletools.filemanager: Package{f2c6674 com.simplemobiletools.filemanager}
09-19 14:15:11.034  1399  2403 V PackageManager: getApplicationInfo com.android.contacts: Package{3938939 com.android.contacts}
09-19 14:15:11.036  1399  2367 V PackageManager: getApplicationInfo com.simplemobiletools.filemanager: Package{f2c6674 com.simplemobiletools.filemanager}
09-19 14:15:11.064  1399  1417 I ActivityManager: Displayed android/com.android.internal.app.ResolverActivity: +343ms
09-19 14:15:11.076  1716  1716 I View    : setSystemUiVisibility(): visibility = 0
09-19 14:15:11.078  1716  1716 I View    : setSystemUiVisibility() call stack: android.view.View.setSystemUiVisibility(View.java:19372);com.android.systemui.statusbar.phone.NavigationBarView.updateNaviHide(NavigationBarView.java:1203);com.android.systemui.statusbar.phone.Navigation`

**Comment by tibbi** [comment]
that was an ancient app version, retry with the latest Pro one
