### ISSUE TITLE
please provide me correct file of mainActivity.java of this project as fast as possible. please it is very urgent

### ISSUE THREAD

**Issue by prakharlakshakar** [SimpleMobileTools/Simple-File-Manager#247]
the MainActivity.java file is showing:
1. An error that it can not find the R object.
please provide me the appropriate code for this project i need it very urgent . as fast as possible , please help me!! @tibbi @tibbi

**Comment by tibbi** [comment]
Well, it is MainActivity.java.

**Comment by prakharlakshakar** [comment]
can you please publish same project in java!! please!! @tibbi

**Comment by tibbi** [comment]
no, the projects are written in kotlin
