### ISSUE TITLE
Can't open avi files

### ISSUE THREAD

**Issue by sheychen290** [SimpleMobileTools/Simple-File-Manager#249]
When opening avi files in see: "com.google.android.exoplayer2.ExoPlayerPlaybackException" and video doesn't start.
It's maybe because in Simple-Commons
```put("avi", "video/x-msvideo")```
and not ```"video/avi"```

**Comment by tibbi** [comment]
so it is a gallery issue, not a file manager one. If you open the file via the gallery (so no file manager will be included), does it work?

**Comment by sheychen290** [comment]
It doesn't work (same screen).
So it's a gallery problem.

Note: VLC can read it

**Comment by tibbi** [comment]
ok, anyway Im aware of the issue as multiple people reported it. It isnt related to a specific file format, happens to videos in general. Ill close it as it belongs to the gallery.
