### ISSUE TITLE
Implement real "move files" (instead copy+delete)

### ISSUE THREAD

**Issue by Klimmbimmel** [SimpleMobileTools/Simple-File-Manager#255]
Currently Simple-File-Manager does not move files, but it copies them and deletes the original. Thus it takes long for bigger files and can be interrupted easily. Somehow this behaviour seems to be ancient computer software style, am I right? I didn't see this certain way to move files since years :)

**Comment by tibbi** [comment]
ye, move was deleting files to people in some cases that I couldnt reproduce and fix, so for now I chose the safer way of copy/delete. Ill give it another try someday

**Comment by tibbi** [comment]
will be added in 4.2.0 if moving from internal storage to internal storage, let me know if it misbehaves.
