### ISSUE TITLE
Creation of some essential documents for Simple file manager.

### ISSUE THREAD

**Issue by HarryHeights** [SimpleMobileTools/Simple-File-Manager#257]
Hello, I'm Harry. I'm a writer on the open-source  community. I mostly contribute to open source projects by creating or drafting some needful documents.

For Simple mobile tools, I can create a compilation of FAQs and their respective answers. I'll create an About us document for the app and then if necessary a privacy policy.

I hope to hear from you soon.

**Comment by tibbi** [comment]
I have those, thanks
