### ISSUE TITLE
The app closes while you rename or delete a folder on the SD card

### ISSUE THREAD

**Issue by wine** [SimpleMobileTools/Simple-File-Manager#26]
Hello, I have the following issues on my Android 6.0.1 device:

Renaming a folder:
- Go to SD card root
- Create a folder
- Long press the new folder and select Rename
- Change the name and confirm
- Crash!

Deleting a non-empty folder:
- Go to SD card root
- Create a folder and open it
- Create a file
- Go back to SD card root
- Long press the previously created folder and select Delete
- Tap anywhere to confirm deletion
- Crash!

Thank you!

**Comment by tibbi** [comment]
awkward crashes, thanks for reporting :)
