### ISSUE TITLE
Folders with empty names

### ISSUE THREAD

**Issue by DHosseiny** [SimpleMobileTools/Simple-File-Manager#266]
Hi! I included your library code in my project and I changed it a lot but don't touched read files list logic. I don't know what is exact version I used but
com.simplemobiletools:commons:2.25.3
is the commons dependency version.
Is this bug fixed? can you please send me fix commit link?
[image](https://ibb.co/npLFCe)

**Comment by tibbi** [comment]
4.6.10 is the latest version o f the Commons library. Anyway it is not meant to be used by other projects, so Im not not giving any support for it. Ive never seen such a glitch.
