### ISSUE TITLE
Option to not sort folders on top

### ISSUE THREAD

**Issue by nyanpasu64** [SimpleMobileTools/Simple-File-Manager#267]
Currently folders are always sorted on top, which is rather annoying since my Downloads folder (which I set to sort as "most recent on top") ends up sorting a screenful of old folders above my new files.

**Comment by balduin-kowalski** [comment]
I would also really like to have this option!

**Comment by tibbi** [comment]
I dont plan adding it, a Recents tab has been added already for recently used files
