### ISSUE TITLE
Ability to browse external SD

### ISSUE THREAD

**Issue by smarquespt** [SimpleMobileTools/Simple-File-Manager#27]
Is it me or we can't explore the SD card?

**Comment by tibbi** [comment]
If you click on the "Internal", a storage picker should pop up. However if you have Android 4, it might not work properly.

**Comment by smarquespt** [comment]
@tibbi 
I have 4.3 version and when I click on Internal, the popup only shows Internal and Root

**Comment by tibbi** [comment]
yeah SD card is not shown properly on Android 4 as I dont have any device for testing it, and it has to be done differently. Ill try adding some implementation soon.

**Comment by smarquespt** [comment]
If I go to /root/storage I can access to SD card.

**Comment by TheKourosh** [comment]
Really like the app but because of this problem, became useless for me :(

**Comment by tibbi** [comment]
Try getting to the SD card folder through the Root folder and add it to favorites, or make it the home folder. If you have Android 4.x you wont be able to do file operations tho, as google messed it up.

**Comment by tidux** [comment]
This works but it's completely non intuitive.  Can you make the area around the word "Internal" a raised button or something?  Until I found this bug report I thought the app was just lying about sdcard and root access.

**Comment by tibbi** [comment]
ye it will definitely be changed, not sure yet how :)
