### ISSUE TITLE
Folder transformed in file while renaming, contained data lost?

### ISSUE THREAD

**Issue by eauchat** [SimpleMobileTools/Simple-File-Manager#277]
Hello, I don't know exactly what the issue is, maybe it's more than one. But here is what I did:

1- Create a folder (it's name contained some special characters, maybe the problem could come from that??: characters I used: ç à - digits, letters and spaces)

2- Put documents in this folder

3- Rename the folder:
  long tap on the folder
  click on the rename icon
  rename to another name with similar characters as the first one

---> what happened:
What was a folder is not a folder anymore, it's now shown as a file. If I try to get info about this file, it tells me the file doesn't exist, if I try renaming it again, it tells me it fails but actually does it (sometimes, not always it seems, that I really don't get). I also tried renaming the file from other file managers, and some show errors, but still seem to succeed renaming it.

The biggest problem for me now is that I've no idea how to recover the content that was in the folder!!
Any suggestion on that?

And it would be cool to do something about the issue so that the same problem doesn't occur to other people too.

Apart from that, thank you for the nice app :)

**Comment by tibbi** [comment]
So far I havent heard anyone mentioning such issue. So if you try renaming a folder without any special chars, it works fine? What app version and Android OS version do you have? Is the folder on an SD card, or internal storage?

**Comment by tibbi** [comment]
it is an ancient app version, reopen if it happens in the pro version 6+
