### ISSUE TITLE
Possible permission issue when selecting a ringtone

### ISSUE THREAD

**Issue by MickeyKnox** [SimpleMobileTools/Simple-File-Manager#278]
I've been using this app on replicant and used it to select a ringtone, which rendered the Setting app / Sounds unusable. The suggested solution was to remove the Simple File Manager, which actually did the trick. 

The issue for replicant is here: https://redmine.replicant.us/issues/1894

**Comment by tibbi** [comment]
@MickeyKnox Is it crashing always as you go into the settings? If I send you a test version, can you try it? Are you using any other apps from the Simple Mobile Tools suite that works fine?

**Comment by tibbi** [comment]
I just released a new version 4.3.1, test that one if you can please.

**Comment by tibbi** [comment]
this is an old thing, shouldnt happen anymore
