### ISSUE TITLE
When sorting by Size, selecting "Root" storage don't work

### ISSUE THREAD

**Issue by aspineux** [SimpleMobileTools/Simple-File-Manager#279]
When sorted by "Name" I can select between "internal", "SD Card" and "Root" 
but when I select "sorted by Size", It is not possible to go into the "Root" storage.
"Root" show up in the list, but selecting "Root" don't do anything while the two other works.

**Comment by tibbi** [comment]
I dont think it still happens. Anyway, Root will be removed altogether in 6.8.5+ on unrooted devices
