### ISSUE TITLE
Accented characters are not allowed in Rename and Create dialogs

### ISSUE THREAD

**Issue by wine** [SimpleMobileTools/Simple-File-Manager#28]
When I try to rename/create a file/folder with a name like **déjà-vu** or **résumé**, I see:

> The name contains invalid characters

I think it's a bug because I can do this using another file manager.

**Comment by tibbi** [comment]
yes the allowed characters are quite restrictive, Ill rework it

**Comment by wine** [comment]
Maybe you can use a try/catch block or similar rather than a regex, so every char supported by Android/filesystem could be used. Just my 2 cents.

**Comment by tibbi** [comment]
ye maybe, I might use something like that instead of a whitelist

**Comment by tibbi** [comment]
should be better now
