### ISSUE TITLE
"File Manager has stopped" after upgrading to Version 5.0.0 (2018-10-11)

### ISSUE THREAD

**Issue by dirtygardner** [SimpleMobileTools/Simple-File-Manager#283]
`uname -a` : Linux localhost 3.4.113-lineageos-g0ed263d #1 SMP PREEMPT Tue Oct 2 01:41:37 UTC 2018 armv7l

[logcat-20181013010000UTC-klte.txt](https://github.com/SimpleMobileTools/Simple-File-Manager/files/2475014/logcat-20181013010000UTC-klte.txt)

`cat logcat-20181013010000UTC-klte.txt | grep filemanager` : 
10-13 01:02:15.881   487  1418 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.simplemobiletools.filemanager/.activities.SplashActivity.Orange bnds=[35,825][237,1068]} from uid 10028
10-13 01:02:15.914   487   534 I ActivityManager: Start proc 3373:com.simplemobiletools.filemanager/u0a96 for activity com.simplemobiletools.filemanager/.activities.SplashActivity.Orange
10-13 01:02:16.084   487  2210 I ActivityManager: START u0 {cmp=com.simplemobiletools.filemanager/.activities.MainActivity} from uid 10096
10-13 01:02:16.207  3373  3373 E AndroidRuntime: Process: com.simplemobiletools.filemanager, PID: 3373
10-13 01:02:16.207  3373  3373 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.simplemobiletools.filemanager/com.simplemobiletools.filemanager.activities.MainActivity}: android.view.InflateException: Binary XML file line #8: Binary XML file line #50: Binary XML file line #50: Error inflating class com.simplemobiletools.commons.views.MyFloatingActionButton
10-13 01:02:16.207  3373  3373 E AndroidRuntime: 	at com.simplemobiletools.filemanager.fragments.ItemsFragment.onCreateView(SourceFile:51)
10-13 01:02:16.207  3373  3373 E AndroidRuntime: 	at com.simplemobiletools.filemanager.activities.MainActivity.onCreate(SourceFile:44)
10-13 01:02:16.207  3373  3373 E AndroidRuntime: 	at com.simplemobiletools.filemanager.fragments.ItemsFragment.onCreateView(SourceFile:51)
10-13 01:02:16.207  3373  3373 E AndroidRuntime: 	at com.simplemobiletools.filemanager.activities.MainActivity.onCreate(SourceFile:44)
10-13 01:02:16.216   487   533 W ActivityManager:   Force finishing activity com.simplemobiletools.filemanager/.activities.MainActivity
10-13 01:02:16.231   487   567 I ActivityManager: Showing crash dialog for package com.simplemobiletools.filemanager u0
10-13 01:02:16.718   487   566 W ActivityManager: Activity pause timeout for ActivityRecord{708416e u0 com.simplemobiletools.filemanager/.activities.MainActivity t139 f}
10-13 01:02:17.864   487   533 I ActivityManager: Killing 3373:com.simplemobiletools.filemanager/u0a96 (adj 900): crash
10-13 01:02:17.899   487   533 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.simplemobiletools.filemanager/.activities.SplashActivity} from uid 10028
10-13 01:02:17.899   487   533 W ActivityManager: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.simplemobiletools.filemanager/.activities.SplashActivity } from null (pid=-1, uid=10028) not exported from uid 10096
10-13 01:02:18.858   487  2213 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.simplemobiletools.filemanager/.activities.SplashActivity.Orange bnds=[35,825][237,1068]} from uid 10028
10-13 01:02:18.877   487   534 I ActivityManager: Start proc 3411:com.simplemobiletools.filemanager/u0a96 for activity com.simplemobiletools.filemanager/.activities.SplashActivity.Orange
10-13 01:02:19.003   487  1398 I ActivityManager: START u0 {cmp=com.simplemobiletools.filemanager/.activities.MainActivity} from uid 10096
10-13 01:02:19.112  3411  3411 E AndroidRuntime: Process: com.simplemobiletools.filemanager, PID: 3411
10-13 01:02:19.112  3411  3411 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.simplemobiletools.filemanager/com.simplemobiletools.filemanager.activities.MainActivity}: android.view.InflateException: Binary XML file line #8: Binary XML file line #50: Binary XML file line #50: Error inflating class com.simplemobiletools.commons.views.MyFloatingActionButton
10-13 01:02:19.112  3411  3411 E AndroidRuntime: 	at com.simplemobiletools.filemanager.fragments.ItemsFragment.onCreateView(SourceFile:51)
10-13 01:02:19.112  3411  3411 E AndroidRuntime: 	at com.simplemobiletools.filemanager.activities.MainActivity.onCreate(SourceFile:44)
10-13 01:02:19.113  3411  3411 E AndroidRuntime: 	at com.simplemobiletools.filemanager.fragments.ItemsFragment.onCreateView(SourceFile:51)
10-13 01:02:19.113  3411  3411 E AndroidRuntime: 	at com.simplemobiletools.filemanager.activities.MainActivity.onCreate(SourceFile:44)
10-13 01:02:19.116   487  1011 W ActivityManager:   Force finishing activity com.simplemobiletools.filemanager/.activities.MainActivity
10-13 01:02:19.120   487   567 I ActivityManager: Showing crash dialog for package com.simplemobiletools.filemanager u0
10-13 01:02:19.618   487   566 W ActivityManager: Activity pause timeout for ActivityRecord{3cc6deb u0 com.simplemobiletools.filemanager/.activities.MainActivity t140 f}
10-13 01:02:20.177   487  1011 I ActivityManager: Killing 3411:com.simplemobiletools.filemanager/u0a96 (adj 900): crash
10-13 01:02:20.202   487  1011 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.simplemobiletools.filemanager/.activities.SplashActivity} from uid 10028
10-13 01:02:20.202   487  1011 W ActivityManager: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.simplemobiletools.filemanager/.activities.SplashActivity } from null (pid=-1, uid=10028) not exported from uid 10096
10-13 01:02:20.814   487   962 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.simplemobiletools.filemanager/.activities.SplashActivity.Orange bnds=[35,825][237,1068]} from uid 10028
10-13 01:02:20.840   487   534 I ActivityManager: Start proc 3459:com.simplemobiletools.filemanager/u0a96 for activity com.simplemobiletools.filemanager/.activities.SplashActivity.Orange
10-13 01:02:20.966   487  1011 I ActivityManager: START u0 {cmp=com.simplemobiletools.filemanager/.activities.MainActivity} from uid 10096
10-13 01:02:21.063  3459  3459 E AndroidRuntime: Process: com.simplemobiletools.filemanager, PID: 3459
10-13 01:02:21.063  3459  3459 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.simplemobiletools.filemanager/com.simplemobiletools.filemanager.activities.MainActivity}: android.view.InflateException: Binary XML file line #8: Binary XML file line #50: Binary XML file line #50: Error inflating class com.simplemobiletools.commons.views.MyFloatingActionButton
10-13 01:02:21.063  3459  3459 E AndroidRuntime: 	at com.simplemobiletools.filemanager.fragments.ItemsFragment.onCreateView(SourceFile:51)
10-13 01:02:21.063  3459  3459 E AndroidRuntime: 	at com.simplemobiletools.filemanager.activities.MainActivity.onCreate(SourceFile:44)
10-13 01:02:21.065  3459  3459 E AndroidRuntime: 	at com.simplemobiletools.filemanager.fragments.ItemsFragment.onCreateView(SourceFile:51)
10-13 01:02:21.065  3459  3459 E AndroidRuntime: 	at com.simplemobiletools.filemanager.activities.MainActivity.onCreate(SourceFile:44)
10-13 01:02:21.068   487   884 W ActivityManager:   Force finishing activity com.simplemobiletools.filemanager/.activities.MainActivity
10-13 01:02:21.072   487   567 I ActivityManager: Showing crash dialog for package com.simplemobiletools.filemanager u0
10-13 01:02:21.570   487   566 W ActivityManager: Activity pause timeout for ActivityRecord{ff8f78f u0 com.simplemobiletools.filemanager/.activities.MainActivity t141 f}
10-13 01:02:21.594   487   566 I WindowManager: Failed to capture screenshot of Token{92a1c ActivityRecord{ff8f78f u0 com.simplemobiletools.filemanager/.activities.MainActivity t141 f}} appWin=Window{2a5ac69 u0 Splash Screen com.simplemobiletools.filemanager EXITING} drawState=4
10-13 01:02:21.728   487   884 I ActivityManager: Killing 3459:com.simplemobiletools.filemanager/u0a96 (adj 199): crash
10-13 01:02:21.758   487   884 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.simplemobiletools.filemanager/.activities.SplashActivity} from uid 10028
10-13 01:02:21.758   487   884 W ActivityManager: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.simplemobiletools.filemanager/.activities.SplashActivity } from null (pid=-1, uid=10028) not exported from uid 10096

**Comment by tibbi** [comment]
not sure why does it happen. If you totally uninstall the app so it isnt visible even at the app settings, then install, does it work already?

**Comment by dirtygardner** [comment]
Uninstalled Version 4.3.1, installed Version 5.0.0, still get "File Manager has stopped".

**Comment by tibbi** [comment]
hm ok, retry version 5.0.1 released soon. Reopen if it is still broken. Thanks

**Comment by dirtygardner** [comment]
Same error persists in Version 5.0.1

**Comment by dirtygardner** [comment]
Issue appears to be gone in Version 5.0.3
Thanks!
