### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by unknowtech** [SimpleMobileTools/Simple-File-Manager#284]
Hello when I copy to the crash apps (it closes) 

version code: 58
version name: 5.0.0
target sdk: 28

thank

**Comment by contrapunctus-1** [comment]
Similarly, I'm experiencing crashes when trying to move files in folders in Android/media/ (e.g. OGG files in `Android/data/com.github.axet.audiorecorder/`)

SFM v5.0 from F-Droid, Android v8.1, Nokia 6.1

**Comment by tibbi** [comment]
is it crashing after you selected the destination folder already, or right after the destination picker dialog appears?

**Comment by unknowtech** [comment]
just after pressing copy to 

thank

**Comment by unknowtech** [comment]
[Video crash](https://mega.nz/#!jzwhnQiB!joZZkZK3sAUOj3246MC__kzb1k1u6rJJycM9NMVyS9c)

**Comment by tibbi** [comment]
ok retry with 5.0.1 released soon, it has some crashfixes

**Comment by tibbi** [comment]
actually Ill close it, reopen if it is still crashing

**Comment by contrapunctus-1** [comment]
Just tried again with v5.0.1 - I'm afraid it still persists.

**Comment by unknowtech** [comment]
the bug is still present

**Comment by user9321w** [comment]
Hello, this crash you are all describing is true yes,, when pressing COPY, from SD card, it crashes. BUT, removing the app entirely and then downloading the latest apk 5.0.1 solves the problem, atleast on 2 phones i tried, android 7.0.1 and android 8.0.
You cant install this app on top of the app you installed from f-droid because its got different signature, so its a bit of a hassle removing and then setting your settings again. i didnt have time to wait for f-droid update.
just feedback! :)

**Comment by unknowtech** [comment]
the problem is fixed with the github version, but is always present from fdroid

**Comment by wilmarcdw** [comment]
Sadly, experiencing another set of crashes with 5.0.1 from F-Droid.
1. The behavior mentioned above. Selecting file(s) and choosing Copy To from menu results in crash.
2. Manage Favorites in settings. Soon as I start to scroll the app crashes.
Cleared cache and data to no avail.

**Comment by tibbi** [comment]
ok, retry with 5.0.2 that will be released on google play soon please

**Comment by wilmarcdw** [comment]
Couldn't test on the original ROM as your tools were initially installed as
system files (replacing default apps).
On another ROM (Nougat) and device I first installed 5.0.1 via F-Droid just
to make sure the problems weren't Oreo-specific. It crashed. Uninstalled.
Installed 5.0.2 from Play Store. Gave it a workout. No crashes at all.
Selecting and copying files or managing favorites all working fine. Great
job. :-)
