### ISSUE TITLE
Some characters are sometimes displayed incorrectly

### ISSUE THREAD

**Issue by Lettendo** [SimpleMobileTools/Simple-File-Manager#287]
For example the character "ō" is sometimes displayed as "ĹŤ". I only noticed this bug so far in mp3 files in the artist field (file properties). Please note that this only happens sometimes. I also checked if the files itself are corrupted but that doesn't seem to be the case.

**Comment by tibbi** [comment]
does it still happen? If it does, please reopen this with a sample file.
