### ISSUE TITLE
Changing capitalization of one letter in file-name

### ISSUE THREAD

**Issue by dirtygardner** [SimpleMobileTools/Simple-File-Manager#289]
Simple-File-Manager-6.0.0
Changing capitalization of one letter in file-name: "A file or folder with that name already exists" message appears.

Model: SM-G900R4
Android version: 8.1.0
LineageOS version: 15.1-20181002-NIGHTLY-klte

**Comment by tibbi** [comment]
should be fixed in 6.9.4
