### ISSUE TITLE
Superuser rights granted toast shown every time the app is restarted

### ISSUE THREAD

**Issue by PopeRigby** [SimpleMobileTools/Simple-File-Manager#291]
Every time the app is closed (swiped away in overview or force killed) the toast with "File manager was granted Superuser rights" is shown. It is expected for this to only happen when you first grant file manager superuser rights. 

[Screenshot](https://photos.app.goo.gl/1QNJmiD1HHBF7J3N7)

**Comment by dl200010** [comment]
This would be Magisk Manager doing this. You can turn off toasts inside of the Superuser section in Magisk Manager.

**Comment by tibbi** [comment]
cannot reproduce it. Apps are not supposed to be force killed anyway, unexpected behaviour is expected in those cases.
