### ISSUE TITLE
Silent failure when writing to SD Card

### ISSUE THREAD

**Issue by contrapunctus-1** [SimpleMobileTools/Simple-File-Manager#303]
Until v6.0.2 (not sure about v6.1), writing to SD Card would give an error (something like 'a problem occurred'), but the operation itself would succeed. In v6.1.1, the operation just fails silently.

Nokia 6.1, Android v9 (Pie), all versions were installed from F-Droid.

**Comment by tibbi** [comment]
you mean copying a file from internal storage to SD card fails? Try finding the app in your device settings and using "Clear Data". It wont delete any files, just reset your app settings and maybe reobtain the SD card path properly.

**Comment by contrapunctus-1** [comment]
Sorry, this was some hardware weirdness. Not a SFM problem.
