### ISSUE TITLE
/root/data unavailable

### ISSUE THREAD

**Issue by smarquespt** [SimpleMobileTools/Simple-File-Manager#31]
When I try to access to /root/data there are no files in there. But with other fm I can access the folder and see a bunch of files.

**Comment by guest4711** [comment]
See also #61

**Comment by tibbi** [comment]
retest with 2.2.2 please, not sure how do things around root folders work

**Comment by guest4711** [comment]
I'll do so when f-droid build is available... Thanx for your support.

**Comment by guest4711** [comment]
Tested with 2.2.2 (from apkpure. f-droid version not ready yet).
Still not asking for root permission. /data

**Comment by smarquespt** [comment]
Same here.

**Comment by beerisgood** [comment]
Can confirm that 2.2.2 (F-Droid version) dont show root content nor ask for root rights.
LineageOS 14.1 (Android 7.1.2)

**Comment by mtbu** [comment]
For me the only way I can see files in the root directory '/' is to move the apk to /system/priv-app/ so it gets system privileges but even then it can't see in /data or modify anything.

Using version 2.3.1 from F-Droid on LineageOS 14.1

**Comment by tibbi** [comment]
should be better with 3.2.0
