### ISSUE TITLE
[Feature Request] Option to Set Default Storage

### ISSUE THREAD

**Issue by CurtisLeeBolin** [SimpleMobileTools/Simple-File-Manager#314]
The first thing I do every time I start the app is change the "Select storage" from "Internal" to "SD Card".  It would be nice to have a default option in settings so I don't have to change it every time I start the app.  Besides this small frustration, great app!

**Comment by tibbi** [comment]
you can already go to the target folder and use Menu -> Set as home folder.

**Comment by CurtisLeeBolin** [comment]
Thank you.  This exactly what I needed.
