### ISSUE TITLE
Make Some Options Available On Bottom

### ISSUE THREAD

**Issue by puppykickr** [SimpleMobileTools/Simple-File-Manager#316]
Feature Request:

Your Gallery app has the availability of including quick menu options at the bottom of the screen.

It would be great if some user selected settings options would appear at the bottom of the screen when a file/folder was long pressed.

Maybe have it pop up like it does in your Gallery app (with a long press, rather than the tap that brings it up in Gallery)?

**Comment by tibbi** [comment]
moving action buttons at the bottom is on the roadmap. It affects most apps though and is reported in General-Discussion so Ill remove it from here
