### ISSUE TITLE
"This operation works only on rooted devices" when attempting to do most things other than rename.

### ISSUE THREAD

**Issue by kiriya-aoi** [SimpleMobileTools/Simple-File-Manager#318]
Simple File Manager Pro, issue occurs on Lenovo TB-X605F, Android 8.1, but not on my phone running 9.0. Issue also does not occur on the tablet using the old non-pro app.

**Comment by tibbi** [comment]
what app version are you using?

**Comment by kiriya-aoi** [comment]
Version is latest from Google Play, but I have inadvertently "solved" it. My path was Root/sdcard/ instead of Internal/, and after switching it works normally. I can no longer get back to the old view where things weren't working.
