### ISSUE TITLE
Action bar with common operations

### ISSUE THREAD

**Issue by smarquespt** [SimpleMobileTools/Simple-File-Manager#32]
Now to make an option we have to click on 3dot menu to do them.

Maybe you could make an action bar with more common actions like:

Cut
Copy
Move
Delete
Select all/Unselect all

**Comment by tibbi** [comment]
The general rule of all apps is a simple UI, so I dont want to flood the screen with extra buttons. In case somebody needs them, he can find them really easily.

**Comment by smarquespt** [comment]
The idea was only to show them when a file/folder is selected. Similar to the information icon that we now have. If nothing was selected nothing was shown. But i get you point.
