### ISSUE TITLE
Opening .xml file causes app to become unresponsive

### ISSUE THREAD

**Issue by dirtygardner** [SimpleMobileTools/Simple-File-Manager#323]
Simple-File-Manager_6.1.2
[
open compound_CID_3776.xml (https://pubchem.ncbi.nlm.nih.gov/rest/pug_view/data/compound/3776/XML/?response_type=save&response_basename=compound_CID_3776); 
app becomes unresponsive
]

**Comment by tibbi** [comment]
what is the size of the file? Isnt it something really huge?

**Comment by dirtygardner** [comment]
1.2MB

**Comment by tibbi** [comment]
guess this works already, file opening has been moved onto a background thread. Even if it takes some time, the app should stay responsive.
