### ISSUE TITLE
[feature request] swipe left / right to access different folders

### ISSUE THREAD

**Issue by tusch001** [SimpleMobileTools/Simple-File-Manager#325]
If you are copying more than one file it takes quite a lot of taps to switch back and forth between different folders. 

My suggestion for improving UI:
Make a home where you have shortcuts to internal / external SD, favorites (feature request by user tippi which I highly recommend), root (if phone is rooted), remote folders (if implemented) and open these folders in new tabs. Make small icons to identify place (internal SD, external SD, network, cloud storage or custom icon if set) and name tab with path or last part of path if too long. To access folders either allow tapping on label or swiping left / right.
Please allow for more than two open tabs (up to 12?).

That was the way it was done in ES file explorer (I already mentioned I loved that app, version 3.2.5.5 if you want to have a look to get the idea). I still think it was the best user interface of all file browsers apps out there before they started spying on everything.

Thx

Patricia

**Comment by tibbi** [comment]
it isnt on the roadmap now
