### ISSUE TITLE
[Feature Request]: Bring back the old bulk rename

### ISSUE THREAD

**Issue by Noryub** [SimpleMobileTools/Simple-File-Manager#331]
"Append" and "Preappend" are better than (%time) options, bring it back please!
(If you can keep both options for files and folders, it would be even better.)

**Comment by Edocsil** [comment]
Honestly the bulk renaming as it is it's pretty much useless outside of a very specific situation. It should have a %name and %extension at the very least... Currently I have no other choice than to have solid explorer installed exclusively for bulk renaming _sigh_ Perhaps do something similar? Please?!

![Screenshot_20190714-140943](https://user-images.githubusercontent.com/2257988/61183398-195b2700-a641-11e9-80e6-f5a21c2dd152.png)
