### ISSUE TITLE
CustomizationActivity changes its state after a screen orientation change

### ISSUE THREAD

**Issue by dlicse** [SimpleMobileTools/Simple-File-Manager#334]
When I change the orientation of the device screen, CustomizationActivity changes its state. Below there are different examples: the screenshots were taken before and after the screen orientation change and they are paired (before, after), (before, after) ...

-- first case --
The color in the background changes
![2019-07-17 17-02-21_before](https://user-images.githubusercontent.com/53469180/62211858-df5b8600-b39f-11e9-929c-83be6d1941d6.png)
![2019-07-17 17-02-21_after](https://user-images.githubusercontent.com/53469180/62211859-df5b8600-b39f-11e9-9766-ab8a0cc3af10.png)

-- second case --
"Add to dictionary" options disappear
![2019-07-17 17-00-39_before](https://user-images.githubusercontent.com/53469180/62211860-df5b8600-b39f-11e9-99dc-66def3da6ab8.png)
![2019-07-17 17-00-39_after](https://user-images.githubusercontent.com/53469180/62211861-dff41c80-b39f-11e9-8710-6c18dc9e0d6c.png)

**Comment by tibbi** [comment]
nothing to fix there, those are not issues
