### ISSUE TITLE
FavoritesActivity loses the object selected after a screen orientation change

### ISSUE THREAD

**Issue by dlicse** [SimpleMobileTools/Simple-File-Manager#335]
When I change the orientation of the device screen, FavoritesActivity loses the selected object.
![2019-07-17 17-04-35_before](https://user-images.githubusercontent.com/53469180/62212054-3e20ff80-b3a0-11e9-8c49-816b3333b448.png)
![2019-07-17 17-04-35_after](https://user-images.githubusercontent.com/53469180/62212055-3e20ff80-b3a0-11e9-9c1c-bd179e9ef702.png)

**Comment by tibbi** [comment]
nothing to fix there, those are not issues
