### ISSUE TITLE
MainActivity changes its state after a screen orientation change

### ISSUE THREAD

**Issue by dlicse** [SimpleMobileTools/Simple-File-Manager#336]
When I change the orientation of the device screen, MainActivity changes its state. Below there are different examples: the screenshots were taken before and after the screen orientation change and they are paired (before, after), (before, after) ...

-- first case --
It loses two options from the menu
![2019-07-17 13-15-04_before](https://user-images.githubusercontent.com/53469180/62212118-690b5380-b3a0-11e9-854d-9c02830db292.png)
![2019-07-17 13-15-04_after](https://user-images.githubusercontent.com/53469180/62212119-690b5380-b3a0-11e9-851d-82cbe70c6a1d.png)

-- second case --
A TextView appears
![2019-07-17 12-44-02_before](https://user-images.githubusercontent.com/53469180/62212120-690b5380-b3a0-11e9-9ba5-a8a3446920cf.png)
![2019-07-17 12-44-02_after](https://user-images.githubusercontent.com/53469180/62212121-69a3ea00-b3a0-11e9-970d-11e6855a1ced.png)

-- third case --
The menu disappears and it also loses the selected object
![2019-07-17 12-20-41_before](https://user-images.githubusercontent.com/53469180/62212123-69a3ea00-b3a0-11e9-9390-09c2183613dd.png)
![2019-07-17 12-20-41_after](https://user-images.githubusercontent.com/53469180/62212124-69a3ea00-b3a0-11e9-81eb-579ded4f60f9.png)

-- fourth case --
The color of the background changes
![2019-07-17 12-10-18_before](https://user-images.githubusercontent.com/53469180/62212125-69a3ea00-b3a0-11e9-8054-e2d405551ac6.png)
![2019-07-17 12-10-18_after](https://user-images.githubusercontent.com/53469180/62212126-6a3c8080-b3a0-11e9-974f-2d0b55b873f4.png)

-- fifth case --
The text written inside the search bar disappears
![2019-07-17 12-08-34_before](https://user-images.githubusercontent.com/53469180/62212129-6a3c8080-b3a0-11e9-93f1-f59bb6094a1f.png)
![2019-07-17 12-08-34_after](https://user-images.githubusercontent.com/53469180/62212130-6ad51700-b3a0-11e9-8c1f-6d8f4eab9948.png)

**Comment by tibbi** [comment]
nothing to fix there, those are not issues
