### ISSUE TITLE
[BUG] Unlock in Pattern Mode is bugged after a Mistake

### ISSUE THREAD

**Issue by Noryub** [SimpleMobileTools/Simple-File-Manager#338]
**HAPPENS ON EVERY SIMPLE MOBILE TOOL APP.**

Block the app, restart, draw an incorrect unlock pattern, and then if you try again, the new pattern that you will draw will erase itself. (Sometimes)

You need to restart the app to fix it.

**Comment by tibbi** [comment]
just wait for the wrong pattern to disappear, then it works well
