### ISSUE TITLE
internal / root option disappear

### ISSUE THREAD

**Issue by arthur-star** [SimpleMobileTools/Simple-File-Manager#339]
## steps to reproduce
On a not rooted device

1. Click internal / root option
2. Set root as home folder 
3. Close and reopen the app
4. internal / root option disappear
5. Cannot set internal as home folder

## expected result

* internal or root option is still there.

## observed behavior

* internal / root option disappear

## versions

    Hardware: HUAWEI MATE 10, not rooted
    v 5.0.4 from Google Play

**Comment by tibbi** [comment]
that is an old app version, it should work with the Pro one 6.3.3
