### ISSUE TITLE
Add Search function

### ISSUE THREAD

**Issue by smarquespt** [SimpleMobileTools/Simple-File-Manager#34]

**Comment by itmike** [comment]
and/or a filter function, eg. "*.apk"

**Comment by tibbi** [comment]
so its regex

**Comment by tibbi** [comment]
search will be improved in 6.2.0, it will search in subfolders too.

**Comment by contrapunctus-1** [comment]
Wanted to chime in with some input on the search function (v6.2 from F-Droid) - the recursive search takes a while to return results, and it's unclear if the search has actually begun or not (it displays "no items found" until the results are found). It should be made incremental (so results are displayed as soon as each is found, not all at once after a gap), and/or there should be a search progress bar/spinner.

**Comment by tibbi** [comment]
progressive recursive search has already been added, regex might come in the further future
