### ISSUE TITLE
Keep "Date modified" when copying files (Root enabled)

### ISSUE THREAD

**Issue by mario-g98** [SimpleMobileTools/Simple-File-Manager#344]
Can you please add the ability to keep the "date modified" attribute when copying files.
The main advantage for me is that when I copy some images they still can be sorted and viewed by date.

Copied with Simpe File Manager
![Screenshot_20190817-123614_1](https://user-images.githubusercontent.com/49582442/63210284-a7b54380-c0ec-11e9-9faa-5978424a6006.jpg)

Copied with Solid Explorer
![Screenshot_20190817-123622_1](https://user-images.githubusercontent.com/49582442/63210281-99672780-c0ec-11e9-98c8-0423643c9033.jpg)

**Comment by tibbi** [comment]
there has been a discussion about this at the gallery right nowadays at https://github.com/SimpleMobileTools/Simple-Gallery/issues/1109#event-2563826977 , it will hopefully be fixed in the next app version released soon. Copy/move is handled by Simple Commons, so it is reused by all apps.

**Comment by tibbi** [comment]
Ill close this, the fix should be added in the new version 6.3.5 released soon
