### ISSUE TITLE
Toolbar button inconsistency

### ISSUE THREAD

**Issue by arthur-star** [SimpleMobileTools/Simple-File-Manager#345]
<div align=center>
<img src="https://user-images.githubusercontent.com/53738161/63634029-94255200-c683-11e9-9d0b-539e0267491e.jpg"  width="50%" height="50%">
</div>

## observed behavior

* Sometimes search icon and home icon disappear.

## expected result

* Search icon and home icon still there.

## versions

    Hardware: HUAWEI MATE 10, not rooted
    v6.3.3

**Comment by tibbi** [comment]
when does it happen? After using search, or so?

**Comment by arthur-star** [comment]
Right, after using search

**Comment by tibbi** [comment]
Ill close this here as it affects multiple apps and should be reported at general discussion too. Sadly the way the system handles that search element is ridiculous, hope one day they fix it, or we will reimplement it on our own.
