### ISSUE TITLE
Sort by date seems not right

### ISSUE THREAD

**Issue by arthur-star** [SimpleMobileTools/Simple-File-Manager#346]
## observed behavior

<div align=center>
<img src="https://user-images.githubusercontent.com/53738161/63634366-d355a200-c687-11e9-8445-ac749d860ed7.png"  width="50%" height="50%">
</div>

* Filename shows the image create date, but seems not consistent.

## versions

    Hardware: HUAWEI MATE 10, not rooted
    v6.3.3

**Comment by tibbi** [comment]
last modified date seems ok on the right side
