### ISSUE TITLE
Setting drop-down theme inconsistency

### ISSUE THREAD

**Issue by arthur-star** [SimpleMobileTools/Simple-File-Manager#347]
## Setp to reproduce

1. Set Black & white theme
2. Click Setting button

## observed behavior

<div align=center>
<img src="https://user-images.githubusercontent.com/53738161/63634576-ffbeed80-c68a-11e9-8287-76bf4b5cb424.png"  width="50%" height="50%">
</div>

the theme did not applied in the dropdown.

## expected behavior

the theme applied in the dropdown.

## versions

    Hardware: HUAWEI MATE 10, not rooted
    v6.3.3

**Comment by tibbi** [comment]
it applies to all apps
