### ISSUE TITLE
Some color issues

### ISSUE THREAD

**Issue by arthur-star** [SimpleMobileTools/Simple-File-Manager#348]
Ref link: https://github.com/SimpleMobileTools/Simple-Gallery/issues/251

May be still confusing for the state of swipe buttons.

<div align=center>
<img src="https://user-images.githubusercontent.com/53738161/63634758-6fce7300-c68d-11e9-86a0-1a713b7b443a.png"  width="50%" height="50%">
</div>

**Comment by tibbi** [comment]
not an issue
