### ISSUE TITLE
Hidden button disappear sometimes

### ISSUE THREAD

**Issue by arthur-star** [SimpleMobileTools/Simple-File-Manager#349]
<div align=center>
<img src="https://user-images.githubusercontent.com/53738161/63634868-e881ff00-c68e-11e9-9f06-a59405543a27.png"  width="50%" height="50%">
</div>

## observed behavior

* Sometimes hidden button disappear.

## expected result

* hidden button still there.

## versions

    Hardware: HUAWEI MATE 10, not rooted
    v6.3.3

**Comment by tibbi** [comment]
because you have hidden item showing enabled already

**Comment by arthur-star** [comment]
But there is no button for undoing hidden mode.

**Comment by tibbi** [comment]
it is in the app settings
