### ISSUE TITLE
What's your plan for Android Q?

### ISSUE THREAD

**Issue by staltz** [SimpleMobileTools/Simple-File-Manager#358]
Hello fellow FOSS developer, I build the [Manyverse](https://github.com/staltz/manyverse) app which is also on F-Droid.

Have you heard of Google's schedule to deprecate shared external directories? [See this article](https://www.xda-developers.com/android-q-storage-access-framework-scoped-storage/).

Your app uses `Environment.getExternalStorageDirectory()` which Google is [deprecating in API level 29](https://developer.android.com/reference/android/os/Environment#getExternalStorageDirectory()).

https://github.com/SimpleMobileTools/Simple-Commons/blob/b6bce2b2ec9a9b89f449648e627dfc1cd783ec7a/commons/src/main/kotlin/com/simplemobiletools/commons/extensions/Context.kt#L188

I think this is terrible news from Google, and I'd like to use `getExternalStorageDirectory()` too. This change in Android Q will affect all File Managers and significantly change the UX and possible features for users. I would like to know if you have any ideas what could be done.

**Comment by tibbi** [comment]
I havent checked it yet. It just sucks that Google changes the way files are handled in every single Android OS version. Instead of fixing the issue it keeps getting worse.

**Comment by tibbi** [comment]
it seems to still work just fine with Android 10 and target/compile sdk 29. Ill release a new version and see if there are any issues at all, I couldnt find any new bug.

**Comment by tibbi** [comment]
actually ye, a clean app install makes "file.list()" return null, Ill see what can be done about it

**Comment by tibbi** [comment]
I guess the solution will be the way in which Solid Explorer did it. At launching the app for the first time the user will have to confirm the storage access and the top of the internal storage with the SAF dialog, like at handling SD card files. It is a horrible thing indeed, but for now it looks like it will be enforced only at releasing Android R around November 2020, so Ill work on it only later.
