### ISSUE TITLE
Make folders searchable and openable in search results

### ISSUE THREAD

**Issue by sokolgeo** [SimpleMobileTools/Simple-File-Manager#359]
1. Right now the program apparently could not search folders by name, only files are searched. Could please folders be made searchable too?
2. When file is found, it is quite often to me when I want to open the parent folder containing this file and not the file itself. The parent folder is shown in search results but it is not clickable/open from search results.

Can these two points please be addressed?

**Comment by tibbi** [comment]
both have been added already
