### ISSUE TITLE
[feature request] Google Samba Plugin Support

### ISSUE THREAD

**Issue by holgerbohni** [SimpleMobileTools/Simple-File-Manager#365]
Dear Tibbi,
there's an Samba Plugin from Google on F-Droid/Github: [https://github.com/google/samba-documents-provider](url), which works pretty well with different types of SMB Shares. 
You may mount a share and it will be displayed in the standard android file manager - a similiar display as a root folder within SimpleFileManager would be very nice. I know, you will not implement it, if it requires different permissions. Thats absolutely ok, just close this request - neither worries nor reply needed. :-)

Thank you very much for your tools!

Cheers
holgerbohni

**Comment by tibbi** [comment]
yeah, it needs internet access, so dont expect having it

**Comment by holgerbohni** [comment]
thanks for your answer and all the best! -holgerbohni
