### ISSUE TITLE
When opening images in SimpleGallery, swiping left/right does not respect the folder's sorting

### ISSUE THREAD

**Issue by shadow00** [SimpleMobileTools/Simple-File-Manager#369]
I have a folder with pictures sorted by last date modified (which are not in alphabetical order), only in that folder.

If I open a picture from that folder in the File Manager in the Simple Gallery Pro app, and I swipe left/right to go to the previous/next picture, the Gallery app is not aware of the sorting choice, and will instead show the pictures in the default alphabetical order.

Therefore, the only way to view pictures in any different sorting order is to open them one by one from the File Manager app.

Closing and reopening either app does not affect this behaviour.

Is there any way to make the Gallery app use the same sorting choice as the File Manager?

**Comment by tibbi** [comment]
no, the apps are standalone, sorting is not shared. Sharing the sorting could become unpredictable, I dont want to add such confusing features
