### ISSUE TITLE
[UX] Some suggestions that might improve file manager UX

### ISSUE THREAD

**Issue by HenriqueCarloFarina** [SimpleMobileTools/Simple-File-Manager#378]
Hi guys, really love the app and project, just want to share a few suggestions that might be pretty quick to implement and could potentially improve UX on the file manager:
1) If from main screen on the file manager one could click just one button and have the favourites showing (I would suggest a favourites button close to home icon on top).
2) when moving or copying it would be nice to be able to pick directly a destination from the favourite locations.
3) when moving or copying, it would be nice also if while navigating the folders looking for a destination one was able to have the folders showing "sorted by" the usual "sort by" setting one uses on the rest of the app.
4) having root and internal on the top path line in the form of root/internal so that when one is inside another folder one can go back to "internal" without having to click 2 times, at present one clicks "internal" and than has to choose between root and internal, if one had root/internal one could already click on the desired level.

**Comment by tibbi** [comment]
Hey, please create a separate issue per suggestion, it cannot be managed like this. I dont like the 4 though, people use Root only really rarely so I dont want to show it to everyone.

**Comment by HenriqueCarloFarina** [comment]
Hi Tibor, thanks for the fast feedback I will open new ones, as I mentioned they are all suggestions and I am totally happy for you to decide which ones are aligned or not with your plans for the app. I will create individual items. I agree with you on 4 that having "root" on screen all times would be ugly, there is probably a better solution. The main UX annoyance I was trying to solve with suggestion 4 is that, if the user is on a folder like "internal/documents/notes" when the user clicks on the "documents" part of the path he is taken in one click to "documents" folder, but when he clicks on "internal" he needs one extra click to get to the "internal" folder as he is presented with the 2 options "root" and "internal" and as you mentioned he will very rarely want to go to "root" so that extra click seems a bit of a waste, maybe you could make "root" accessible only from the "internal" folder (once it is used very rarely) or have an option on settings that defines the behaviour of the "internal" button. Anyway, maybe there is an even better solution and I am not seeing it.
