### ISSUE TITLE
UX favourites suggestion 1

### ISSUE THREAD

**Issue by HenriqueCarloFarina** [SimpleMobileTools/Simple-File-Manager#379]
It would be great if from the main screen on the file manager one could click just one button and have the favourites showing (I would suggest a favourites button close to home icon on top).

**Comment by TobiasDev** [comment]
I second this. Or adding the standard android drawer that has the favorites at the top or such. :)

**Comment by kocjs** [comment]
+1 for favourites at the top.

**Comment by tibbi** [comment]
it already has a top menu button
