### ISSUE TITLE
UX Behaviour of the [internal] part of the path

### ISSUE THREAD

**Issue by HenriqueCarloFarina** [SimpleMobileTools/Simple-File-Manager#382]
If the user is on a folder like "internal/documents/notes" when the user clicks on the "documents" part of the path he is taken in one click to "documents" folder, but when he clicks on "internal" he needs one extra click to get to the "internal" folder as he is presented with the 2 options "root" and "internal" once he will very rarely want to go to "root" that extra click seems a bit of a waste, maybe you could make "root" accessible only from the "internal" folder (once it is used very rarely) or have an option on settings that defines the behaviour of the "internal" button. Anyway, maybe there is an even better solution and I am not seeing it.

**Comment by Friptick** [comment]
This has been bothering me too, since forever. It is a small but very obvious and annoying UX bug. Every time i update the app I marvel that it still has not been fixed.

@HenriqueCarloFarina's suggested solutions are both sensible.

**Comment by landry314** [comment]
i agree. i have to tap an extra time every time i need to go to my internal directory...

**Comment by tibbi** [comment]
It will work like that from 6.8.5+. Root wont be visible on nonrooted devices at all, so if there is only 1 item (Internal), it will automatically be selected. If you have an SD card there will be 2 items that you have to select from, but I want to keep like that for now.

**Comment by Friptick** [comment]
At last! Now the app is perfect, Thank you,
