### ISSUE TITLE
Reported as risky app by Trend Micro anti virus.

### ISSUE THREAD

**Issue by kuanyui** [SimpleMobileTools/Simple-File-Manager#383]
![Screenshot_20200212-210839_Mobile Security](https://user-images.githubusercontent.com/1370070/74338787-cb2c2300-4ddd-11ea-948c-d30d67f4b40d.jpg)
![Screenshot_20200212-210850_Mobile Security](https://user-images.githubusercontent.com/1370070/74338802-d1220400-4ddd-11ea-89e1-d28c8c8f4810.jpg)

I don't know why, it try to get root permission as long as installed? Other open source file manager like Amaze or GhostComnander (and they have root-related features) didn't trigger this.

**Comment by tibbi** [comment]
I dont know, there are many fake antivirus apps out there. If your device isn't rooted and you don't explicitly allow root access in the app, it obviously cannot access anything root related itself.
