### ISSUE TITLE
Why is decompressing on an OTG drive an issue?

### ISSUE THREAD

**Issue by pandalion98** [SimpleMobileTools/Simple-File-Manager#390]
I was inspecting the code in `adapters/ItemsAdapter.kt` and noticed that, in `decompressSelection()`, it's throwing an unknown error if the file is in OTG, specifically the first path:

```
        val firstPath = getFirstSelectedItemPath()
        if (activity.isPathOnOTG(firstPath)) {
            activity.toast(R.string.unknown_error_occurred)
            return
        }
```

Why is that the case? I don't see a clear reason why.

Possibly related: #260 #193

**Comment by tibbi** [comment]
working with files on USB is a mess, it works differently than on the internal storage or SD card
