### ISSUE TITLE
[Feature Request] Option for WiFi sharing

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [SimpleMobileTools/Simple-File-Manager#397]
This feature would allow Simple File Manager to share files with any other devices while they are connected to the same router, users can do file transfering without USB cable or online cloud services. If this option is enabled, this app would open a specific port during the connection, offer a web based interface to access, edit, download and upload files with web browser. This feature need to run as a background service.

**Comment by tibbi** [comment]
It would require some internet related permissions so dont expect having that. Thanks
