### ISSUE TITLE
WARNING. MainActivity

### ISSUE THREAD

**Issue by WORLD8848** [SimpleMobileTools/Simple-File-Manager#398]
private property name 'BACK_PRESS_TIEOUT' should not contain underscores in the middle or the end
private property name 'PICKED_PATH' should not contain underscores in the middle or the end

The mainActivity source code, above, provides a warning message from the two properties.

Please give me some advice on the solution.

**Comment by tibbi** [comment]
it is self explanatory... But I dont care about such warnings

**Comment by WORLD8848** [comment]
I am grateful for your prompt reply.
 
I'm sorry to ask for a brief explanation of the warning message.
Because I'm learning Kotlin for the first time. 
Please understand.
 
---------------------------------------------

항상 건강하고 행복하세요!

감사합니다.

김성훈 배상

========================================================
김성훈 팀장 (010-9874-8848)

Mail : world8848 (gmail, outlook, naver, live, nate, hotmail.co.kr)
SNS  : world8848 (facebook, twitter, Kakao Talk, WeChat, Line, nate)
========================================================
 
-----Original Message-----
