### ISSUE TITLE
Potential Bug: The app icon keeps disappearing from homescreen

### ISSUE THREAD

**Issue by salman-abedin** [SimpleMobileTools/Simple-File-Manager#401]
I have dragged the icon from my app drawer to my homescreen for quick access but every now and then and after each reboot, the app seems to be getting vanished!

**Comment by tibbi** [comment]
Have you maybe changed the icon color? Some launchers do not handle that properly and just make the icon disappear. You should either change your launcher app, or just stick to the default orange icon.

**Comment by salman-abedin** [comment]
I was hoping you would say anything but this! lol.
I figured as much myself and was hoping it was something else.
Anyway, I guess I'm gonna have kiss that beautiful blue icon goodbye. XD
