### ISSUE TITLE
Implement visibility independently of the file system

### ISSUE THREAD

**Issue by chaserene** [SimpleMobileTools/Simple-File-Manager#402]
Hiding a folder is implemented via renaming the it (adding a period prefix). The issue with this is that 1) it can break apps that rely on that path, and 2) some such apps will just recreate the folder with the original name. So as far as the end result is considered, the folder you hide becomes visible again.

Do you think it's possible to implement visibility as a filter within the app, so that it won't modify anything in the file system (but at least not the item names) and can work independently of it?

**Comment by tibbi** [comment]
I dont plan adding that. Prepending names with a dot is the standard way of hiding files on Linux, so Android too

**Comment by chaserene** [comment]
and do you have any suggestions on how to do hide folders without breaking apps?

**Comment by tibbi** [comment]
what breaks by it?

**Comment by chaserene** [comment]
any app that tries to use a folder that I hide. for example, a bunch of apps litter /storage/emulated/0 with their own program data. if you try to clear up the view by hiding such a folder (e.g. "App"), then App first malfunctions (it can't find the past data, as it's now in ".App"), then recreates the original folder ("App"), filling it up as if it was reinstalled.

as an extra issue, if you don't know this happened because of the hiding in Simple File Manager, you'll have no idea why your config in App was reset.

**Comment by tibbi** [comment]
well you are not really supposed to hide system folders belonging to some apps. That is kind of an Android system issue that app files are lying around everywhere. They try solving it with the new Storage Access Framework, where file access will be really limited.
