### ISSUE TITLE
Move folder along with files

### ISSUE THREAD

**Issue by supersonic118** [SimpleMobileTools/Simple-File-Manager#403]
When you select move I want to be able to move the folder along with the contents inside not just the files inside.

**Comment by cbiere** [comment]
Yes, please.

**Comment by DuMuT6p** [comment]
Hello,
From my expirience the folder is copied, but it also remains empty on the old location. May be the "delete" fails.

**Comment by oonet** [comment]
> the folder is copied, but it also remains empty on the old location.

v 6.8.0. Confirmed.
