### ISSUE TITLE
Can i add Kotlin coroutines in all over app?

### ISSUE THREAD

**Issue by gouri-panda** [SimpleMobileTools/Simple-File-Manager#407]

**Comment by tibbi** [comment]
why would you do it?

**Comment by gouri-panda** [comment]
Coroutines are cheap and easy to use.

**Comment by tibbi** [comment]
and what benefits would it bring to users?

**Comment by gouri-panda** [comment]
- Long running tasks are tasks that take too long to block the main thread.
- Main-safety allows you to ensure that any suspend function can be called from the main thread.

**Comment by tibbi** [comment]
long running tasks already have a separate thread, so I dont want to complicate the code unnecessarily
