### ISSUE TITLE
How To create Folder

### ISSUE THREAD

**Issue by SauravPrsd** [SimpleMobileTools/Simple-File-Manager#409]
I want to create new folder inside my application and show that folder in fragment, not in internal,External storage
I am using Kotlin

**Comment by tibbi** [comment]
well just press the Plus button at the bottom right corner

**Comment by SauravPrsd** [comment]
Sir i am developing my own application in that application i want to create folder programmatically

**Comment by tibbi** [comment]
Im not giving support for third party apps
