### ISSUE TITLE
Scrollable View changes position on Device Rotation

### ISSUE THREAD

**Issue by reverse-unina** [SimpleMobileTools/Simple-File-Manager#41]
When I perform this sequence of events, the scrollable view on screen goes back to the top:

In the main activity:
1. Scroll Down
2. Orientation Change

**Comment by trubitsyn** [comment]
@tibbi does not reproduce at the top level directory. But here's another problem: as soon as I open any child directory, scroll down and rotate, it brings me back to the top directory. I'll create a new issue for that.

**Comment by tibbi** [comment]
works fine already
