### ISSUE TITLE
Rename files

### ISSUE THREAD

**Issue by oonet** [SimpleMobileTools/Simple-File-Manager#418]
Rename files. Individually or as a group.

**Comment by tibbi** [comment]
you can already do that by selecting the wanted files by long pressing them and using the top Menu -> Rename. The icon looks like a cursor.

**Comment by oonet** [comment]
Yes, I see it. I forgot. Since delete is in the menu with move and copy, I expected rename to be there too. Is there a reason to put rename in top place instead of the more customary delete (with an easily recognized trash icon)?

Regardless, rename present and accounted for :-)

**Comment by tibbi** [comment]
well you might need it more, other people might not. I dont want to make it customizable yet, that would be a big mess.

**Comment by oonet** [comment]
No need to change it on my account :-)

Just curious that people want rename to be more convenient than delete. I'm surprised. Not what I'd expect.
