### ISSUE TITLE
File Simple Manager Ignores Recycle Bin of Simple Gallery

### ISSUE THREAD

**Issue by puppykickr** [SimpleMobileTools/Simple-File-Manager#429]
When using Simple Gallery to view files via Simple File Manager, files are deleted instead of first moving to the recycle bin.

Simple Gallery Pro version 6.17.3
Simple File Manager version 6.8.1

**Comment by puppykickr** [comment]
To clarify:

Using Simple File Manager to go through downloaded files, upon selection the file is opened with Simple Gallery Pro.

If the trashcan is inadvertantly touched, the file is immediately deleted instead of moving to the recycle bin.

**Comment by tibbi** [comment]
the apps are unrelated, they cannot browse each others files
