### ISSUE TITLE
[Feature Request] Compact view for photos

### ISSUE THREAD

**Issue by samuelsarao** [SimpleMobileTools/Simple-File-Manager#432]
Hi there! I have a suggestion and a feature request! 

When viewing photos in the folders, especially folders containing lots of pics, it becomes a bit difficult to browse and glance through all of them at once in the default view. I have made a design of how it could look like :) 

One solution is to reduce or increase the column count. However, it's not always handy and it takes time which otherwise could be a quick and easy task. Another solution is to have an option of _'Compact View'._ Where users could switch between the default view and the compact view. This not only makes browsing all the pics quick but also helps when users need to delete, move, copy, and share multiple and large bunch of photos at once. 

Here's the mockup design:

![App Feature Mockup Design.png](https://user-images.githubusercontent.com/73632908/101042305-0d0f9b00-35a3-11eb-846f-07b47cc7b075.png)

Thanks!

**Comment by tibbi** [comment]
I dont really plan adding such view, maybe just toggling thumbnail visibility

**Comment by samuelsarao** [comment]
> I dont really plan adding such view, maybe just toggling thumbnail visibility

It's totally fine :) Thanks for taking your time! <3
