### ISSUE TITLE
[FR] Respect .hidden files

### ISSUE THREAD

**Issue by limbusdev** [SimpleMobileTools/Simple-File-Manager#434]
In most Linux file managers, it is possible to create a file `.hidden` in directories to define files and folders, that should not be displayed, if hidden items are not to be shown. Right now this is not supported in Simple-File-Manager.

Cheers,
Georg

PS: This would fix another issue as well. Right now hiding an item with Simple-File-Manager *renames* that item to have a `.` prefix, which might break apps using specific paths. I think "hiding" an item should mean adding its name to the `.hidden` file, not renaming it.

**Comment by tibbi** [comment]
I dont see any file manager I tried using the .hidden file. Hiding on Linux works by prepending the folder name with a dot, thats the way I want to go, not implementing any custom solutions. My Linux doesnt recognize .hidden either.

**Comment by limbusdev** [comment]
All major desktop file managers (Dolphin, Nautilus, Thunar, PCManFm, ...) support this. Its not some custom behaviour but pretty common for much more than 10 years now. Hiding files with a doz breaks paths which might be the reason for all other (Desktop-)file managers to support this.

Please reconsider this : ) @tibbi

**Comment by limbusdev** [comment]
See the last section in this [itsfoss article](https://itsfoss.com/hide-folders-and-show-hidden-files-in-ubuntu-beginner-trick/)

**Comment by tibbi** [comment]
might be used in ubuntu, but definitely not commonly in Android. I tried quite a few popular file manager apps for it and none supported it

**Comment by limbusdev** [comment]
Not only ubuntu but all linux DEs. Thought it could be a great feature for everyone who is using linux on their pc too. And it doesn't harm to be the first to have a good feature ; ) Just really missed it for years now on android.

Still your choice. 

Cheers

**Comment by limbusdev** [comment]
I can understand, that this is not what you want. I instead forked SimpleFileManager and added this feature for anyone in need of it. Just wanted to let you know ; )

Its not production ready yet, but it works.

https://github.com/limbusdev/Tanooki-File-Manager/

Its great to have it under GPL : ) Thank you

Cheers.

**Comment by htsmi** [comment]
I'd appreciate this too since I have some apps that don't respect the android folder hierarchy and put their data in the root of the SD card. I can't use the hide menu option because that renames the folder. (Honestly that is kind of unexpected and created a messy situation when one of the apps created a new folder before I could rename it back.) In Windows you can set a special attribute and in Linux (desktop at least) the solution is .hidden, but there is no equivalent way of doing it here. I don't see the need to close it, it's just a feature request.

**Comment by lucidtanooki** [comment]
@htsmi  I created a fork with this implemented. You can have a look: https://github.com/limbusdev/Tanooki-File-Manager
