### ISSUE TITLE
Lag when renaming folders

### ISSUE THREAD

**Issue by RickyM7** [SimpleMobileTools/Simple-File-Manager#435]
The app takes a long time to complete the renaming of folders.

Device: Redmi Note 4 - MIUI 11 (Android 7.0)
App version: v6.8.2 (F-Droid)

**Comment by tibbi** [comment]
are they on an SD card? Does the given folder contain a lot of files?

**Comment by RickyM7** [comment]
@tibbi Sorry for the delay.

> are they on an SD card? Does the given folder contain a lot of files?

 No, the folders are in the internal storage and the lag occurs in any folder, regardless of the amount of files.

**Comment by tibbi** [comment]
should be better already

**Comment by RickyM7** [comment]
> should be better already

I've just tested and it's really better now, thank you.
