### ISSUE TITLE
[FR] Move 'Delete' option to quick action bar when selecting files

### ISSUE THREAD

**Issue by anthonymvicente** [SimpleMobileTools/Simple-File-Manager#437]
I don't know if I'm the only one who thinks this, but it'd be really convenient to have the delete option on the quick action bar next to the 'info' and 'rename' actions when selecting files instead of hidden behind the 3 dot menu. I delete files far more than I rename anything.

Dream world would be to allow customizing what shows up there, but I'm curious if anyone else thinks this way along with me.

**Comment by tibbi** [comment]
I dont actually plan moving them, some action buttons will be added at the bottom though, like at the galleries fullscreen view.
