### ISSUE TITLE
[bug] video files are not being played correctly when sorted differently in Simple Gallery

### ISSUE THREAD

**Issue by Wurzelmann** [SimpleMobileTools/Simple-File-Manager#438]
So this bug is rather obscure... :-)

Scenario:

1. Simple File Manager (version 6.8.2 Pro, fdroid)
2. a folder with multiple video files
3. the sorting for said folder is alphabetically

When the same folder has a different file sorting method (for examle last modified) in Simple Gallery (version 6.18.0. pro, fdroid), the file manager does not play the correct files when invoking the Simple Gallery Video Player from the file manager. Instead, it always opens the file, which would be the first one in Simple Gallery with the sorting method there. This results in a rather annoying situation, where I cannot play the correct videos from File Manager, except when both apps use the same file sorting method for said folder.

I hope this explanation is clear, if not, I can provide more in-depth information.

OnePlus 5T
LineageOS (lineage-17.1-20201229)

**Comment by tibbi** [comment]
should be fixed already
