### ISSUE TITLE
When I select Root as (instead of Internal), nothing is shown (instead of having / with sub folders)

### ISSUE THREAD

**Issue by alexandrenavarro** [SimpleMobileTools/Simple-File-Manager#442]
When I select Root as (instead of Internal), nothing is shown (instead of having / with sub folders).

Thanks in advance.

**Comment by tibbi** [comment]
do you have a rooted device? What app version are you using?

**Comment by alexandrenavarro** [comment]
No, my device is not more rooted. But when I used Root Explorer for instance (my previous file manager) I can see the / directory like /dev /etc / config ... It was the reason why I'm suprised not to see the root directory.

**Comment by tibbi** [comment]
starting with 6.8.5 the Root wont even show up if the device is unrooted, that is the expected behaviour I want to have
