### ISSUE TITLE
Make delete confirm dialog more verbose

### ISSUE THREAD

**Issue by ChristianTacke** [SimpleMobileTools/Simple-File-Manager#45]
Hi,

I like the simplicity. But in the case of delete, it would be good, if the confirmation dialog could be more verbose, so that I actually know, what I am going to delete.
This includes:
* If the directory is empty, note that "Do you want to delete an empty directory?"
* If the directory contains something, be even more verbose. This could possibly delete a complete tree with a lot of data.
* When deleting more than one item, at least tell the number of items. I am not actually sure, wether any of the items should be allowed to be a directory with content (previous point).

**Comment by tibbi** [comment]
I dont really want to update those messages, this seems ok. You can clearly see how many items are in which folder, and also the amount of selected items in the actionbar.

**Comment by ChristianTacke** [comment]
Well, it's the question, which user group you are targeting?
* Geeks, who know, what they're doing
* Normal users, who could need a bit of guidance. Not annoying them more than needed.

**Comment by tibbi** [comment]
You dont need to be a geek to know that if 1 folder is selected, 1 folder will be deleted, with everything in it...
