### ISSUE TITLE
Bug: Error when renaming a file and only changing case (upper or lowercase) of character

### ISSUE THREAD

**Issue by cwille97** [SimpleMobileTools/Simple-File-Manager#457]
When renaming a folder from "Books" to "books" I got an error saying "A file or folder with that name already exists". As far as I can tell, it doesn't exist, and the error is referring to the file itself that is being renamed. 

The current workaround for me is to rename "Books" to "Books2" or really anything except for the same name. Then a second rename to go from "Books2" to "books" which was the original name I wanted to swap to.

 I think the fix for this could be as simple as this: if the folder that is causing the conflict is the folder being renamed, we can safely ignore it. 

I am able to replicate this issue, check out the attached video:

https://user-images.githubusercontent.com/24487628/110259311-04997880-7f75-11eb-95a1-e6cd4796ec01.mp4

**Comment by tibbi** [comment]
should be working already
