### ISSUE TITLE
Make fonts larger?

### ISSUE THREAD

**Issue by ChristianTacke** [SimpleMobileTools/Simple-File-Manager#46]
Android 4.2 on an old Galaxy S4.
In system settings, I already have configured font size with "Extra large", but still the font is still tiny. Especially when compared to the stock file browser.

**Comment by Larx** [comment]
I would appreciate that, too. Any progress?

**Comment by tibbi** [comment]
not really working on the file manager now, I will get back to it within a couple weeks.

**Comment by Larx** [comment]
I like the idea behind this app. A simple filemanager is ideal for the not-so-techical user who just wants to access the downloads and so on. Most filemanagers are geared towards the power user, but all those features just disturb the average user.
But for this scenario the usability could still need a few improvements. Looking forward to new versions!
