### ISSUE TITLE
Delete button location + PDF Thumbnail missing + Confirmation

### ISSUE THREAD

**Issue by decodering22** [SimpleMobileTools/Simple-File-Manager#462]
I really want to replace the default samsung file manager like i have with Simple Gallary Pro, but there is a few thing preventing me.

1. User ability UX and ergonomics - On these large phone it is much easier having a delete button at the bottom. Samsung My Files pops up a Move, Copy, Share and Delete menu (Frankly the new Myfiles has more and it's not needed). It is much faster and easier to select the option you want than having to take your hand off to reach to the top of the phone. 

2. Thumbnails of PDF files are not shown while it works on other file managers, if you can fix this it would be great.

3. A way to turn off delete confirmation similar to the Simple Gallery Pro app which I use daily and has replaced the default samsung Gallary app.

Will be happy to test and debug code like I have done for other projects if you can implement these. 

![Screenshot_20210415-093421_My Files](https://user-images.githubusercontent.com/78891534/114905538-e9b8f000-9dcd-11eb-9196-ba55b09f566a.jpg)

**Comment by tibbi** [comment]
Hey, report issues one by one if they havent been reported yet please, it cannot be managed like this.

**Comment by decodering22** [comment]
No problem will do one for each. Some like to keep it together in other repo
