### ISSUE TITLE
Option to turn off Delete Confirmation like Simple Gallary Pro

### ISSUE THREAD

**Issue by decodering22** [SimpleMobileTools/Simple-File-Manager#465]
I really want to replace the default samsung file manager like i have with Simple Gallary Pro, but there is a few thing preventing me.

A way to turn off delete confirmation similar to the Simple Gallery Pro app which I use daily and has replaced the default Samsung Gallary app.

**Comment by decodering22** [comment]
Will be glad to help test and debug like I have for other open source projects.

**Comment by tibbi** [comment]
permanent disabling will be added in 6.9.3
