### ISSUE TITLE
Remove or toggle "Press back again to exit"

### ISSUE THREAD

**Issue by tkterris** [SimpleMobileTools/Simple-File-Manager#468]
Similar to #356 . "Press back again to exit" is a bit frustrating, I'd like to be able to close the app with a single back button press.

If you want, I can create a PR to implement this feature, either as a toggle or removing the double-back-press entirely. Let me know what would be preferred.

**Comment by tibbi** [comment]
you can add a settings item, but keep the current behaviour by default
