### ISSUE TITLE
Name the file to be deleted 

### ISSUE THREAD

**Issue by Kohoshi12** [SimpleMobileTools/Simple-File-Manager#475]
The name of archive or paste to be deleted should appear on the message to confirm the deletion instead of "item". The user could be confused for what item they selected to delete. To avoid any catastrophic file deletion.

**Comment by tibbi** [comment]
What app version are you using? The filename is already shown in 6.9+ if you are deleting 1 item.

**Comment by Kohoshi12** [comment]
6.8.8 the last version available on F-Droid.

**Comment by tibbi** [comment]
right, so update whenever it becomes available
