### ISSUE TITLE
Error message java.lang...

### ISSUE THREAD

**Issue by gbdomubpkm** [SimpleMobileTools/Simple-File-Manager#476]
Update  V 6.9.0 
Used on Volla phone (Volla OS, ANDROID 9 base)

Just after launching the app,  the following message appears at the bottom of the screen (home page of the folder listing) :

an error has occurred :
java.lang.NullPointetException: name must not be null

This message disappears.
On the face of it, no malfunction is detected.

**Comment by tibbi** [comment]
just update to 6.9.2, it has been fixed already

**Comment by gbdomubpkm** [comment]
Ok thanks i didn't know !  Not in F-Droid yet. Just got the update v 6.9.0 yesterday  on F-Droid !
