### ISSUE TITLE
Support for shortcuts ( future request )

### ISSUE THREAD

**Issue by noname-3** [SimpleMobileTools/Simple-File-Manager#484]
Will there be support for shortcuts that collect files from the entire file system that refer to a specific shortcut, music, apk, photos, videos ... and so on?

**Comment by tibbi** [comment]
They are already supported in the Pro version, but only from Android 8

**Comment by noname-3** [comment]
> They are already supported in the Pro version, but only from Android 8

I have android 10, Simple File Manager Pro from the f droid website, I open the file manager and the file system is shown to me without shortcuts

**Comment by tibbi** [comment]
just select a file or folder by long pressing and use the top Menu -> Create shortcut

**Comment by noname-3** [comment]
> just select a file or folder by long pressing and use the top Menu -> Create shortcut

You misunderstood me a little, that's what I meant, you click, let's say, on the archives shortcut and all archives from the entire file system are shown
![XiaomiFileExplorerV1-1906281](https://user-images.githubusercontent.com/62765820/120888148-6f536200-c5ff-11eb-8e3e-7d38b4ca7d81.png)

**Comment by tibbi** [comment]
thats not shortcuts, just some file groups

**Comment by noname-3** [comment]
> это не ярлыки, просто некоторые группы файлов

Will there be support for grouping files like in the screenshot?

**Comment by tibbi** [comment]
not sure, it should be added in the future

**Comment by noname-3** [comment]
> not sure, it should be added in the future

At least a separate tab where a group of files will be collected, please
