### ISSUE TITLE
No "Delete Recent Files History" and Displays hidden apps in "Recent"

### ISSUE THREAD

**Issue by Jam355m1th** [SimpleMobileTools/Simple-File-Manager#485]
Pretty self explaintory. The File Manager does keep a record of the files you have used recently. However, there is no option to delete the record of the files you have recently used. While this may or may not be a concern of single people, those of us who have kids have reason for concern. To be frank, I don't whant my kids getting into picture of an intimate nature, period. That's between me and my wife and no one else. Having said that, that doesn't mean I want or need my kids blocked out from all access to my phone. This is just a basic feature that keeps curious kids out of things they have no business in. My secondary issue is, after files have been hidden and password/patern/finger-print/etc. locked, they are still displayed in the "Recent" tab! How is that for easy access? In short, the "Recent" tab gives free and unfettered access to all of your files, locked, hidden, or otherwise.  Both of these issues present serious impediments to parental control and local/direct-device secirity.

**Comment by tibbi** [comment]
You cannot delete items from the Recents without deleting files themselves, it doesnt work like call history.
