### ISSUE TITLE
Open and edit .txt files from within the app

### ISSUE THREAD

**Issue by ghost** [SimpleMobileTools/Simple-File-Manager#49]
Given that they can be created within the app, it would be great being able to open them and edit them. 

Or... the Simple Notes app could open .txt files too, but that'd be an issue for another app.

But just plain simple text. I don't think it would be wise to start recognizing different syntaxes like MiXplorer does. Just plain .txt is fine.

**Comment by kaecy** [comment]
Hi, check out ted: https://github.com/xgouchet/Ted

**Comment by altaf933** [comment]
Just not limit for .txt file I believe photo can be open through the application.

**Comment by tibbi** [comment]
if you click on a photo a list of Galleries should show up. I dont want to handle images inside the File Manager.

**Comment by altaf933** [comment]
Correct but I noted that whatever file open through a gallery are not allow to move in next/ previous image.

**Comment by tibbi** [comment]
thats a gallery issue already, not an issue of the File Manager. Are you using my Simple Gallery, or a different one?

**Comment by altaf933** [comment]
Off course it may be open issue of Gallery, I have opened the picture in default app **Photos**.

**Comment by morfikov** [comment]
Isn't it better to create another app called for instance Simple Editor, which would be able to open and edit text files? I'm using https://github.com/billthefarmer/editor . It's simple and has I think all the features I want, except maybe history of edited files for simpler use.

**Comment by tibbi** [comment]
.txt opener is actually already implemented. I dont currently plan creating any new apps.
