### ISSUE TITLE
Cannot enter any folders in root, Android 11

### ISSUE THREAD

**Issue by ioogithub** [SimpleMobileTools/Simple-File-Manager#491]
Although I have root enabled in the settings. I can display the folder list in root but tapping on any folder does nothing. Root does not appear to be working.

**Comment by tibbi** [comment]
what app version are you using?

**Comment by ioogithub** [comment]
Version 6.20.1 from F-Droid

**Comment by tibbi** [comment]
You sure it is the File Managers version? Sounds like the version of your gallery.

**Comment by ioogithub** [comment]
Sorry you are correct the version is 6.9.2 from F-Droid. Is the problem because you are targeting SDK29?

I have a few other file managers that seem to be able to navigate root however I really like you suite of apps.

I am on Android 11 (LineageOS 18.1) on Lenovo Z6 Pro

**Comment by tibbi** [comment]
I dont know, Android 11 seems to have changed quite a few things.

**Comment by tibbi** [comment]
duplicate of #490
