### ISSUE TITLE
Feature Request: ".." for parent directory

### ISSUE THREAD

**Issue by SlidingHorn** [SimpleMobileTools/Simple-File-Manager#492]
When I'm approaching my internal storage root, it's annoying to have to tap that, then select it vs my sd card. That particular button should stay for ease of switching between the two, but at the top of the directory listing, there should also be a `..` to move to the parent directory.

**Comment by tibbi** [comment]
what app version are you using?

**Comment by SlidingHorn** [comment]
6.8.0

**Comment by BraINstinct0** [comment]
Seconded.

**Comment by tibbi** [comment]
I dont think this will be added, just press Back or some folder at the top path, you can go up by multiple folders too
