### ISSUE TITLE
Current version not available in F-Droid

### ISSUE THREAD

**Issue by Krawei** [SimpleMobileTools/Simple-File-Manager#493]
Dear team,

when I take a look on google play store the current version is 6.9.3, in the F-Droid store the current version is 6.9.2.

What's the reason for this gap? Is there a bug in the build process?

Please fix this.

Kind Regards,

Krawei

**Comment by tibbi** [comment]
forgot to create a release on Github, added it now. F-droid should eventually fetch it. Thanks
