### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by Pauler221** [SimpleMobileTools/Simple-File-Manager#494]
The search function is simply not working. I cannot search for folders nor files. It shows nothing after I type in a search term.

**Comment by tibbi** [comment]
Hello, isnt it just slow? Try searching in some subfolders. What app version are you using?

**Comment by Pauler221** [comment]
I tried the newest 6.9.3 release form github and the 6.9.2 from f-droid. Both have the same issue. 

Now I tried waiting longer for the results like 15 seconds? And it worked. Thx for the hint! 

But it just says "No items found. Type in at least 2 characters to start the search." So I was confused why it's not searching when it actually was. Didn't know I had to wait. 

Will you add something into the app to make it more clear that its actually searching? Or maybe even speed up the search process? Thx in advance!

**Comment by cunlem** [comment]
Oh so the search does work! I also never bothered to wait long enough for results to appear and just assumed it was broken. I guess it's something in app that needs improvement because searching for files with `find` in Termux works a lot faster.
