### ISSUE TITLE
why the app doesn't use MANAGE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by AdvisedlyAlburn** [SimpleMobileTools/Simple-File-Manager#505]
It can't read Android/data because it doesn't use the new MANAGE_EXTERNAL_STORAGE permission. Why you don't use it instead of READ_EXTERNAL_STORAGE?

**Comment by tibbi** [comment]
the new way of handling /Android/data is more complicated, it is not just some permission. Duplicate of #490
