### ISSUE TITLE
Display "Gratis" Instead of "Libre" in Spanish

### ISSUE THREAD

**Issue by AguanteDebian** [SimpleMobileTools/Simple-File-Manager#517]
Hello. I've found this translation problem in the app. The application in Spanish shows that text saying "Gratis" when in fact it should say "Libre", since "gratis" means "free as free beer" when "libre" means "free as free in space" or "free as in freedom". Thank you a lot for the application, I use it a lot in the day to day work. Greetings.

![photo](https://user-images.githubusercontent.com/93792533/140565124-13030531-eb9d-47fd-a144-12c75587c4bb.jpg)

**Comment by tibbi** [comment]
ye it has been fixed already, will be updated in the next app version. Thanks
