### ISSUE TITLE
Display "Files" Instead of "Archivos" in Spanish

### ISSUE THREAD

**Issue by AguanteDebian** [SimpleMobileTools/Simple-File-Manager#518]
Hi. I've found this option where it displays a word in English when the language of the application is in Spanish. It displays "Files" when it has to be "Archivos" in the Settings menu, in the option Manage shown tabs. Thank you and Greetings

![photo_2021-11-06_12-14-01](https://user-images.githubusercontent.com/93792533/140614566-21062220-5bfc-43bd-8dcb-0c98ecd544ed.jpg)
".

**Comment by tibbi** [comment]
I updated it, will be fixed in the next app version. THanks
