### ISSUE TITLE
Selection Folders In A Directory

### ISSUE THREAD

**Issue by HonestAbe7** [SimpleMobileTools/Simple-File-Manager#522]
I noticed that if I select the last folder in a directory then the first one, it then automatically selects everything in between. For example, if I long press to select folder z then select folder a (or even a then z too), everything is selected when I just want a and z selected and nothing in between. Any chance this could be fixed? This really makes handling folders difficult if I delete something I didn't want to.

**Comment by tibbi** [comment]
Hello, long press only the first item to activate selection mode, then select the next ones by short clicks only.
