### ISSUE TITLE
Overwrite & Keep Both When Copying

### ISSUE THREAD

**Issue by HonestAbe7** [SimpleMobileTools/Simple-File-Manager#523]
I noticed that the overwrite and keep both act the same. So when I updated a file with the same file name and chose "overwrite" I was expecting it to overwrite it. Instead, all it did was add the (1) at the end of the filename for me to change again. Please fix this. Thanks!

**Comment by Aga-C** [comment]
In my devices (Android 11 and Android 6.0.1) this features work as they should. Maybe there are some problems with permissions to write files on your device?

**Comment by HonestAbe7** [comment]
No because I use CX File Explorer with none of the issues I have brought up.

Nov 19, 2021 4:32:40 AM Agnieszka C ***@***.***>:

**Comment by BraINstinct0** [comment]
Regarding permissions that's irrelevant since you might've granted that app permissions a while ago.
Recently application permissikns are getting stricter so would be worth checking permissions at application info, just to be extra sure
