### ISSUE TITLE
"Use for this folder only" option causes mixing grid with list view

### ISSUE THREAD

**Issue by Aga-C** [SimpleMobileTools/Simple-File-Manager#531]
Hi,

I've encountered a strange bug that occurs when using a particular view only for one folder. For example, while having everywhere grid view, after setting list view for one directory, some views get mixed grid view with list view: either list view items are displayed in grid, or grid view items are displayed as a list. This causes other issues, for example when list view items are displayed in a grid, I can't hide file names.

See two videos below that show two different ways to reproduce this issue:

https://user-images.githubusercontent.com/85929121/144645896-2c4c629a-0189-4fdf-8076-cecad75241d6.mp4

https://user-images.githubusercontent.com/85929121/144645926-4f701905-262b-4fd3-9877-2c08c406ce3d.mp4

Videos above are made on emulator (Android 11), but I was also able to reproduce it on a device with Android 11 and Simple File Manager v6.11.0.

BTW. I think that in Storage Analysis tab (without entering particular category), toggle filename visibility button is not needed since it doesn't have any use.

**Comment by tibbi** [comment]
I guess it depends on the Recents files? Maybe some of them come from the one used at "Use for this folder only"?

**Comment by Aga-C** [comment]
Yes, in both places they are from that directory.
