### ISSUE TITLE
Biometric Verification Dialog

### ISSUE THREAD

**Issue by AguanteDebian** [SimpleMobileTools/Simple-File-Manager#534]
Hi. I have enable the Biometric Verification every time I open the File Manager. In the last update on F-Droid, the Dialog that appears at the beggining of the application, I have a problem and a feature request:

1.- The text that displays in the boton of the Biometric Verification of the File Manager is in English althought I have the application in Spanish.

2.- Now been the comprobation from the system and not from the application, my feature request is instead of having to click in "OPEN BIOMETRIC ID VERIFICATION DIALOG" to open the system's Biometric Verification dialog in order to continue to the application normally, Is it posible to open that system dialog at the begging of the application? so this way would cost less touch and more fast access to the File Manager.

Thanks a lot for your the work. Greetings

![a](https://user-images.githubusercontent.com/93792533/144837255-bf448631-531c-456f-8ae4-327c601260a2.jpg)

**Comment by Aga-C** [comment]
You can translate this string on your own, here is how: <https://github.com/SimpleMobileTools/General-Discussion#how-can-i-suggest-an-edit-to-a-file>
This text is in Simple Commons.

**Comment by AguanteDebian** [comment]
Thank you Aga-C ! Now i'm translating the problem and all the word that are in English in the Spanish mode, plus in the 
Simple-Commons repo. Thanks to Aga-C and tibbi! Greetings
