### ISSUE TITLE
Apk icon

### ISSUE THREAD

**Issue by ghost** [SimpleMobileTools/Simple-File-Manager#54]
Please, ad an ability to see the icon of the Apk inside the app!

**Comment by tibbi** [comment]
hello, not sure what you mean, could you describe it more?

**Comment by AlfaOmega33** [comment]
Yes, the first is FileManager, the second is ZArchiver
![screenshot_2017-01-02-21-45-40](https://cloud.githubusercontent.com/assets/22004671/21605341/f417d3e0-d1a8-11e6-9c7b-d95d8b9a780d.png)
![screenshot_2017-01-02-21-45-23](https://cloud.githubusercontent.com/assets/22004671/21605354/05cd97be-d1a9-11e6-9865-73dc3587bba2.png)

**Comment by tibbi** [comment]
aha ok, more types of files need that icon, Ill add them in the future

**Comment by AlfaOmega33** [comment]
Ok, thank you! 

... and sorry for my bad english, I use Google Translator
