### ISSUE TITLE
Can't use the file manager with KeePassDX

### ISSUE THREAD

**Issue by ZeikoFr** [SimpleMobileTools/Simple-File-Manager#540]
Hi,

Just moved to a new phone and wanted to switch from keepassdroid to KeePassDX.

When I try to open a database on keepassDX I encounter this error :+1: 

"A file manager that accepts the ACTION_CREATE_DOCUMENT and ACITON_OPEN_DOCUMENT intent action is required to create, open and save databse files"

This error redirect me here https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync

Does anyone encountered the same issue ?

EDIT : seems like a long press on the field open a "choose an app to open" and propose simple file manager and simple galery, maybe there's a conflict between the 2 apps ?

Regards

**Comment by tibbi** [comment]
not sure, but that is a way too advanced usecase for this app, dont really expect having it

**Comment by ZeikoFr** [comment]
> not sure, but that is a way too advanced usecase for this app, dont really expect having it

Hi, thanks for your answer, but I don't really see the advance use case here ?

The result on a phone that use the OEM file manger is : 

Click on "open database"
File manager open up
Click on the database
Return to keepassDX

And some sort of permissions should already be in the app since I can create a file directly from the file manager ?

Maybe just adding the permission required on the app solve this ? 

I'm not an android dev so sorry if ii'm overlooking some issues

Regards

**Comment by ZeikoFr** [comment]
EDIT :

Long press on "Opening database" open simple file manager

Sorry for the issue, it is working enough to use !

Regards

**Comment by tibbi** [comment]
we do not plan adding support for opening databases
