### ISSUE TITLE
Talkback labels

### ISSUE THREAD

**Issue by davidbtc2009** [SimpleMobileTools/Simple-File-Manager#541]
I noticed that the tabs along the top of the app for files, recent, and storage overview all read as "tab" "tab" "tab" and that the create new button for files and folders reads as "unlabeled" instead of something like "add new"

**Comment by tibbi** [comment]
what app version are you using?

**Comment by davidbtc2009** [comment]
V6.11.2 from F-Droid

Sent from ProtonMail mobile

-------- Original Message --------
