### ISSUE TITLE
Exclude folders to be scanned in recents tab

### ISSUE THREAD

**Issue by yant0** [SimpleMobileTools/Simple-File-Manager#543]
- exclude *path* folder not to be scanned ``/storage/emulated/0/Android/data/com.vanced.android.youtube/cache/exo``
- option to acutally exclude folders not to be scanned
![Imagepipe_275](https://user-images.githubusercontent.com/80298071/147675056-2a937716-bdd9-41f1-bbd6-7386b4c48339.jpg)

**Comment by tibbi** [comment]
has been removed in 6.13.0 already
