### ISSUE TITLE
Password protection can lead to false sense of security

### ISSUE THREAD

**Issue by javaxubuntu** [SimpleMobileTools/Simple-File-Manager#557]
Hi,
It's possible to password-protect this application, but the password is removed if I clear the app's data. Users should be warned that this feature does not provide much security.
This feature would be useful to protect files inside the app's private storage inside /data/data, because "clear data" would also delete the files inside.

**Comment by tibbi** [comment]
there is already a warning after setting up any password that reinstalling the app clears it

**Comment by javaxubuntu** [comment]
For biometrics protection, the message is "Please reinstall the app in case of problems with reseting it". I think it does not really warn about the security issue.
