### ISSUE TITLE
Samba (SMB) support in a LAN

### ISSUE THREAD

**Issue by jviguera** [SimpleMobileTools/Simple-File-Manager#56]
It would be great if the app could access (read/write/copy) files in a samba share in a local network.

Still maintaining the minimal set of permissions to be able to do the task.

**Comment by alpenblauwtje** [comment]
YES!! This was one of the feature requests I was looking for. To have it understandable for normal humans  I'd call it 'Network Locations'. I've tried a lot of File Managers, and I was impressed by the simple though effective way ASUS File Manager implemented network support. A great example.

**Comment by alpenblauwtje** [comment]
BTW I just noticed ASUS FM calls it 'Network storage'. Also note that you can e.g. copy files to a saved network location.

**Comment by dane-lyon** [comment]
We are a training service of the French state and we would also like the Samba (network locations) function on this application. At the moment, we are obliged to use ES Explorer which does not satisfy us anymore.
Simple-File-Manager is exactly what we need for our students.

Thanks a lot !

**Comment by roizcorp** [comment]
+1
SMB would be really great

**Comment by F3000** [comment]
Any ETA of this feature ?

**Comment by tibbi** [comment]
no, it wont come anytime soon

**Comment by okdewit** [comment]
QuickPic is untrustworthy and closed source, and was one of the few gallery managers with network share support. Amaze & Ghost Commander seem to be the only two FOSS file managers with network share support.

It would be amazing if I could browse through the files & photo albums stored on my NAS!

**Comment by tibbi** [comment]
Ill close this as it needs some internet related permissions and that wont be added
