### ISSUE TITLE
Please add sd card tab

### ISSUE THREAD

**Issue by Pranab009** [SimpleMobileTools/Simple-File-Manager#562]
Please sir add sd card tab.
Don't you throughout that it is easier than tap "internal" and change to sd card.

![Screenshot_20220313-202150_1](https://user-images.githubusercontent.com/65340361/158093692-e620b8d4-a7c9-449d-90c5-e906bcaa506f.png)

**Comment by tibbi** [comment]
that isnt on the roadmap

**Comment by Pranab009** [comment]
But why?
You add it as optional features anyone can enable or disable.
Sorry to say but Simple gallery, contact, calendar apps are too good. but some apps are worst like file manager, launcher etc.
Work on this apps.
I'm very old user of Simple mobile tools. Please work on this apps. Don't neglect my words.
