### ISSUE TITLE
Display issue with new update

### ISSUE THREAD

**Issue by siker498** [SimpleMobileTools/Simple-File-Manager#566]
the space between each folder is too small and the icons are huge compared to the last update
![Screenshot_20220323-074941_File Manager](https://user-images.githubusercontent.com/21956733/159693595-40f4d962-510e-4752-ad25-e277149459e1.png)
![Screenshot_20220323-074946_File Manager](https://user-images.githubusercontent.com/21956733/159693599-55ccced1-a3a3-4016-bdd3-8c745cf9534a.png)

**Comment by tibbi** [comment]
spaces arent too small, they are supposed to be smaller than folders. Some placeholder icon size improvements are already on the roadmap.
