### ISSUE TITLE
Server/Cloud Support

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [SimpleMobileTools/Simple-File-Manager#587]
I would greatly appreciate SMB and Cloud drive support. I always need to manage the files on my server via an SMB share with my phone, and being able to use Google Drive, Proton Drive, and others from the app would be insanity convenient. Would this be considered? Thank you.

**Comment by tibbi** [comment]
our apps have no internet access, dont expect having that
