### ISSUE TITLE
Make switch between internal storage and external SD better discernible

### ISSUE THREAD

**Issue by Larx** [SimpleMobileTools/Simple-File-Manager#59]
IMHO currently it is not really intuitive to switch between the different storages. Clicking on a (small lettered) text on top the file list is not self explaining, and moreover you really have to aim to hit it right. 

One solution would be to make a real button. Another solution, e.g. in combination with the also requested bookmarks-feature, might be a swipe-menu from the left

**Comment by tibbi** [comment]
should be better already
