### ISSUE TITLE
can't use another PDF reader to be default

### ISSUE THREAD

**Issue by esmaeelE** [SimpleMobileTools/Simple-File-Manager#594]
After set open PDF with embedded tool there is no way to revert it and set another PDF application to do so. Actually I can open with other reader but can't set it as default.

**Comment by tibbi** [comment]
default apps are stored in the system, just find the default one in your device settings and use Clear Defaults on it.

**Comment by esmaeelE** [comment]
First I check it. There is no default in system.

https://paste.c-net.org/CopiesTraps
Also I check it in other device

**Comment by aricooperdavis** [comment]
> First I check it. There is no default in system.
> 
> https://paste.c-net.org/CopiesTraps
> Also I check it in other device

The way to clear the default is to open the File Manager app info and clear the defaults there:

![Screenshot_2022-08-01-13-20-22-420_com.mi.android.globallauncher.jpg](https://user-images.githubusercontent.com/8947634/182146419-56e578fa-da7a-4fa2-95d8-644e5596fecd.jpg)
![Screenshot_2022-08-01-13-19-06-961_com.miui.securitycenter.jpg](https://user-images.githubusercontent.com/8947634/182146435-6b101a63-c0da-48cc-a6af-f04559656df8.jpg)
