### ISSUE TITLE
[feature idea] Simple e-pub viewer

### ISSUE THREAD

**Issue by gbdomubpkm** [SimpleMobileTools/Simple-File-Manager#596]
Hello.
Thank you very much for the simple pdf file reader which works very well.
Would it also be possible to include a simple e-pub file reader? I will very much like this in your app which requires a minimum number of permissions therefore of quality.
Regards

**Comment by tibbi** [comment]
what do you mean by epub? Arent they pdfs?

**Comment by gbdomubpkm** [comment]
I speak of that 
https://filesamples.com/formats/epub

**Comment by tibbi** [comment]
that isnt on the roadmap for this app
