### ISSUE TITLE
Moving files on sd card takes more than 2x the time that it takes to copy them

### ISSUE THREAD

**Issue by pezcurrel** [SimpleMobileTools/Simple-File-Manager#604]
Using Simple File Manager to move a 307 mb directory with 62 jpg files from one directory on my phone's "external" sd card to another directory on my phone's "external" sd card (same partition) takes 40 seconds; copying the same directory takes 18 seconds.
On the internal sd card both operations take 16 seconds.

**Comment by tibbi** [comment]
what app and OS version are you using?

**Comment by pezcurrel** [comment]
> what app and OS version are you using?

SFM 6.12.4 Pro, Android 9

**Comment by pezcurrel** [comment]
Sorry, I tried reproducing it now for 3 times and couldn't so probably I messed up something when making tests for this issue, https://github.com/SimpleMobileTools/Simple-File-Manager/issues/603, that I can reproduce always.
I'll close this, sorry again, please have a look at the other one though :)

**Comment by tibbi** [comment]
well I am doing copy/delete in some cases indeed, just to double check that the file has been copied properly before deleting the original one. File operations on Android are ridiculous and it keeps changing with every damn new OS version, so it is better to be a bit slower than to delete some files.
