### ISSUE TITLE
Incorrect bottom French text

### ISSUE THREAD

**Issue by heberjeur** [SimpleMobileTools/Simple-File-Manager#608]
Hi, I'm using the lastest version 6.12.5 and I can't see all the text of "Analyse du stockage"
I have Samsung A50, Android 11

![Screenshot_20220702-121344_File Manager](https://user-images.githubusercontent.com/11852634/176998876-6297d7cd-5707-4206-b5d5-6c58129619e0.jpg)

**Comment by tibbi** [comment]
will be fixed in the next app version

**Comment by heberjeur** [comment]
It's Stockage and not Storage 
![Screenshot_20220710-084100_File Manager](https://user-images.githubusercontent.com/11852634/178142619-9ddc4b2a-3279-414b-996b-22a21ebb2d0b.jpg)
