### ISSUE TITLE
Folders show up in "Recent" Tab

### ISSUE THREAD

**Issue by NWuensche** [SimpleMobileTools/Simple-File-Manager#613]
The recent tab shows folders. However, as it assumes there are no folders in the list, it shows them as an "unknown file" which you cannot open.

How to reproduce:

1. Create new Folder `X` (through FAB)
2. Open X
3. Add new File `Y` (through FAB)
4. Go to Recent-Tab
5. See `X` at the top of list

Here is an example (Folders where called `vh` and `Test`):

![2022 07 17 15-34-15](https://user-images.githubusercontent.com/15856197/179400958-bfd98428-0ab2-4038-a8a6-281a9b550327.png)

Done on a Moto G7 with Android 11 and 12.

**Comment by tibbi** [comment]
will be fixed in 6.13.0
