### ISSUE TITLE
Embedded PDFium is dated, has ~5/~60 CVE's

### ISSUE THREAD

**Issue by ltGuillaume** [SimpleMobileTools/Simple-File-Manager#619]
Depending on whether https://github.com/DineroRegnskab/PdfiumAndroid/commit/92366356e8cec369d6ec083bc411e8e7d9224e94 actually updated the libraries to March 2021 (M90) versions, which is unclear to me, there are at best 5 known security issues, at worst ~80.

See:
https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=PDFium
https://divestos.org/misc/appsec.txt

**Comment by tibbi** [comment]
I dont understand those geeky things there, what can happen to an app without internet access?

**Comment by ltGuillaume** [comment]
It doesn't need to. The payload is the PDF itself. That can contain the malicious code perfectly fine. There are too many dynamic components to the PDF standard.

**Comment by lipici** [comment]
Thanks for reporting this.

**Comment by jondo** [comment]
What is PDFium used for? Could that use be disabled as a quick mitigation?

**Comment by SkewedZeppelin** [comment]
PDF viewing:
- https://github.com/SimpleMobileTools/Simple-File-Manager/blob/master/app/src/main/res/menu/menu_pdf_viewer.xml
- https://github.com/SimpleMobileTools/Simple-File-Manager/blob/master/app/src/main/res/layout/activity_pdf_viewer.xml
- https://github.com/SimpleMobileTools/Simple-File-Manager/blob/master/app/src/main/kotlin/com/simplemobiletools/filemanager/pro/helpers/PdfDocumentAdapter.kt
- https://github.com/SimpleMobileTools/Simple-File-Manager/blob/master/app/src/main/kotlin/com/simplemobiletools/filemanager/pro/activities/PDFViewerActivity.kt

**Comment by jondo** [comment]
Hmm, I'd prefer leaving PDF viewing to a specialized app, like [MuPDF](https://mupdf.com/). Wouldn't that be "simpler"?

**Comment by Aga-C** [comment]
> Hmm, I'd prefer leaving PDF viewing to a specialized app, like [MuPDF](https://mupdf.com/). Wouldn't that be "simpler"?

I was in favor of a separate PDF app from the beginning (see https://github.com/SimpleMobileTools/Simple-File-Manager/issues/585), and I am using the mentioned app right now (I think it's the simplest PDF app, but too simple and there is still no suitable app).

**Comment by TwizzyDizzy** [comment]
> Hmm, I'd prefer leaving PDF viewing to a specialized app, like [MuPDF](https://mupdf.com/). Wouldn't that be "simpler"?

Very much in favour of this sentiment. For every kind of media/files to be opened. I see the convenience aspect of not having to install additional apps if you just want to peek at files. But then again: probably nobody would use FileManager to actually listen to music for the usability aspects that are (usually) better in a dedicated player.

Just my two cents...

Cheers
Thomas

**Comment by BrendonIrwan** [comment]
It'd be best to remove the PDF functionality really. After all, its a Simple File Manager, not a Document File Manager. My guess is that the integration of a PDF ~~~reader~~~ editor is inspired from web browsers, which are also (web) document viewers.

**Comment by BrendonIrwan** [comment]
It'd be best to remove the PDF functionality really. After all, its a Simple File Manager, not a Document File Manager. My guess is that the integration of a PDF ~~~reader~~~ editor is inspired from web browsers, which are also (web) document viewers.

**Comment by BrendonIrwan** [comment]
It'd be best to remove the PDF functionality really. After all, its a Simple File Manager, not a Document File Manager. My guess is that the integration of a PDF ~~~reader~~~ editor is inspired from web browsers, which are also (web) document viewers.

**Comment by tibbi** [comment]
will be fixed in 6.14.4

**Comment by engineer22** [comment]
> will be fixed in 6.14.4

Just because I'm wary of this stuff, I _need to_ ask. Any estimate on when the next version will release?

**Comment by BrendonIrwan** [comment]
> will be fixed in 6.14.4
Your consideration is much, much appreciated.

> Just because I'm wary of this stuff, I _need to_ ask. Any estimate on when the next version will release?

If it matters, just try not to load any PDFs for now.

**Comment by tibbi** [comment]
I want to tweak 1-2 more things in it, then Ill update it within the next few days

**Comment by imsi32** [comment]
It seems like you just changed PDFViewer to voghdev's PDFViewPager, however it is not updated in 1 year. This project is probably not maintained at this moment so it is not take any security updates for 1 years.

Is it really okey to use this PDF Viewer. I think you should separate PDF viewer to other application. I think just saying there's no Internet connection in app do not prove security. I really like your apps but I just don't want to use unsecured apps which can affect all system.

**Comment by SkewedZeppelin** [comment]
@imsi32 

The new library uses the built-in system functions for actual PDF processing and adds no native code. It should be safe.

**Comment by lipici** [comment]
Im not convinced. Shoudnt be released a separate version without pdf viewer ?

**Comment by LearningAsIGo71** [comment]
I agree. There is no need for a file manager to have a native PDF viewer. The longer this issue remains outstanding the longer time there is for Simple Mobile Tools reputation to be damaged. Let the user decide what PDF viewer they want to open PDFs in. For example, I use GrapheneOS for privacy and it comes with its own PDF Viewer.

**Comment by OkyDooky** [comment]
>Let the user decide what PDF viewer they want to open PDFs in.

Isn't that a built-in feature in the Android OS? If you clear default associations and have multiple apps that can natively open PDFs, it should ask you which one you want to use after tapping on a PDF file. That's what it does for me and it just gives this apps PDF Viewer/Reader as an option, even if I'm opening it from, say, Amaze.

**Comment by rokejulianlockhart** [comment]
@OkyDooky, yes, it's a feature provided by Android, but a developer can bypass this by hardcoding it.
