### ISSUE TITLE
When I make another app based on this open source and when I launch it, it shows a message to download on the website simplemobiletools.com

### ISSUE THREAD

**Issue by dxn1234** [SimpleMobileTools/Simple-File-Manager#629]
When I make another app based on this open source and when I launch it, it shows a message: You are using fake version of the app. For your own safety download the orginal one from www.simplemobiletools.com. And i can not run my the project. How to delete dialog notice of open source Simple-File-Manager and i can run my source code normal ???

**Comment by tibbi** [comment]
ye, you are not supposed to republish the app

**Comment by dxn1234** [comment]
No I don't republish the app. I only rely on  open source for
reference on how to do functions in my project

Vào 14:19, Th 3, 23 thg 8, 2022 Tibor Kaputa ***@***.***> đã
viết:
