### ISSUE TITLE
Swipe Between Photos Opened From File Manager

### ISSUE THREAD

**Issue by seniorm0ment** [SimpleMobileTools/Simple-File-Manager#633]
If you go to SimpleMobileTools File Manager, open a photo, you are unable to swipe left or right to view other photos in that current directory. 
It would be very nice to be able to see them.

**Comment by tibbi** [comment]
that is handled by the used gallery, it is not open in the file manager

**Comment by seniorm0ment** [comment]
The used Gallery is SimpleMobileGallery. So do you want me to open the issue in that repo...?

**Comment by tibbi** [comment]
ye, you can. But add additional details like app and OS version plus exact steps
