### ISSUE TITLE
 Crash when write or delete file or folder on external SD card

### ISSUE THREAD

**Issue by RoestVrijStaal** [SimpleMobileTools/Simple-File-Manager#64]
Simple File Manager version: 2.1.0 (but it occurs for months)
Android: 6

I'd wish to add a log here, but catlog can't filter easy. 

It seems Simple File Manager uses an old API?

**Comment by tibbi** [comment]
Hello, what old API you mean? Can you try reinstalling the app just so things clear up? Do you get an additional SD card write permission dialog when you try doing some file operation on an SD card for the first time?

**Comment by RoestVrijStaal** [comment]
Hi, 

I deleted cache & data and uninstalled the app. 
After turning the phone off and on avian, I installed the app. 
I get indeed the additional SD card write permission dialog when accessing the external SD card for the first time. 
However after accepting SFM still crashes when writing to the external SD card. 

With "Old API" I mean the way how files could be read and written before Google disallowed apps to write to external SD card.

**Comment by tibbi** [comment]
Ill take a look at the crashdumps. Google keeps changing SD card handling in every single Android version, its a nightmare to work with.

**Comment by tibbi** [comment]
it should be fixed already, let me know if not

**Comment by RoestVrijStaal** [comment]
Hmmmmm it (still?) doesn't. I've it tested with 2.2.2 now.

**Comment by tibbi** [comment]
hm, then ill reopen it

**Comment by Lonami** [comment]
I can confirm, it crashes. You never ask for external SD card access permission on newer devices. You do ask for writing to the internal storage, but not "Select the SD card folder" annoying thing.

**Comment by tibbi** [comment]
its all inside the Commons library already, reused by multiple apps. Ill try updating the file manager, hasnt been updated for quite a while

**Comment by tibbi** [comment]
Do you have Android 7.x? Lineage or so? Ive had the chance to test Android 7 only on a Nexus 9, that worked fine. File handling on Android is getting more difficult with every new version. If you could send me an email to hello@simplemobiletools.com and helped debugging it that would be appreciated. Thanks

**Comment by Lonami** [comment]
> Do you have Android 7.x?

6.0.

> File handling on Android is getting more difficult with every new version. 

I couldn't agree more.

> and helped debugging it that would be appreciated.

What do I do? Fetch upstream version and test it?

**Comment by tibbi** [comment]
If you wrote me an email I could send an attachment there with a build that you could test. Anyway can you test this version Im attaching? You have to have installing apps from unknown sources enabled in the security settings of your device. Rename "app-release.zip" to "app-release.apk" and install it, github doesnt allow uploading apk files. There will be a message popping up as you run the app, can you tell whats written on it, or take a screenshot of the message? Thanks
[app-release.zip](https://github.com/SimpleMobileTools/Simple-File-Manager/files/1085969/app-release.zip)

**Comment by Lonami** [comment]
> You have to have installing apps from unknown sources

Please I'm a developer too :P

**Comment by Lonami** [comment]
I tested your build and granted permission (though it was asking for screen overlay, and for some reason, I couldn't enable it – I had to enable storage from Android Settings instead), but it still crashes when I try to create a file on SD card. It did not ask me to select the SD card folder.

**Comment by tibbi** [comment]
heh right, Im getting confused by who is who, I have a lot of email communication too :) Anyway Ive found out that its happening to me too so I could fix it easily. Just try building the latest master then, should be working. That screen overlay was related to the toast message, it was enough to wait till it disappears. Its an extra permissions related security thing
