### ISSUE TITLE
Files from hidden folders are visible in "Recents".

### ISSUE THREAD

**Issue by unihorn78** [SimpleMobileTools/Simple-File-Manager#648]
Subj.

Files from hidden folders are visible in "Recents". This makes it pointless to password-lock hidden folders.

If you have a special emphasis on privacy, then this is a VERY BIG problem.

Possible solutions to the problem:

1) add a button to clear "Recents" without physically deleting files in "Recents", only clearing the list (as in FileManager+);

2) "forcibly" display files in "Recents" from hidden folders as "hidden" (regardless of whether they are "really" hidden (showing such files should be linked to the "Temporarily show hidden" function with all related operations (entering a password (if available), etc.)));

3) a combination of options 1 and 2 (THE MOST IDEAL OPTION).

**Comment by Ilav1** [comment]
It seems like simple file manager isn't the problem. I'm using privacy browser. The developer wrote, that it's a Google download bug (see here https://redmine.stoutner.com/issues/915).

**Comment by Ilav1** [comment]
It seems like simple file manager isn't the problem. I'm using privacy browser. The developer wrote, that it's a Google download bug (see here https://redmine.stoutner.com/issues/915).

**Comment by kdadmin** [comment]
Related - adding a button to clear "Recents" without physically deleting files would be nice - the list has many many files in it which I find annoying.

**Comment by gradha** [comment]
Option to disable completely history would be nice too, I have no use for such a feature at all.

**Comment by tibbi** [comment]
well, just hide the Recents tab then

**Comment by tibbi** [comment]
hidden files shouldnt be shown anymore in recents
