### ISSUE TITLE
Rename of downloaded duplicate

### ISSUE THREAD

**Issue by Ilav1** [SimpleMobileTools/Simple-File-Manager#650]
I often have the problem, when I download something twice (same names) the app is rename the second file. The second file has (1) at the end of the filename.

The problem is that the file type is changing. For example look at the screenshoot:

![Screenshot_20221029_094408_com android gallery3d_1](https://user-images.githubusercontent.com/102852954/198820202-c8737b56-238d-4b4d-a66c-aa9de3f9cf69.jpg)

The second file isn't a pdf file, it's a ".pdf (1)" file so I can't open it anymore. I have to rename the file. It would be better to add the (1) in the first part of the names so it still is the same ending.

**Comment by tibbi** [comment]
what folders does it happen to?

**Comment by Ilav1** [comment]
Every folder

**Comment by Aga-C** [comment]
It works on my phone:
![image](https://user-images.githubusercontent.com/85929121/198821892-5a96b8cb-0caf-4c28-848d-1416361a7e4e.png)

What are the reproduction steps?

**Comment by Ilav1** [comment]
It seems like simple file manager isn't the problem. I'm using privacy browser. The developer wrote, that it's a Google download bug (see here https://redmine.stoutner.com/issues/915).

**Comment by Ilav1** [comment]
It seems like simple file manager isn't the problem. I'm using privacy browser. The developer wrote, that it's a Google download bug (see here https://redmine.stoutner.com/issues/915).

**Comment by Ilav1** [comment]
It seems like simple file manager isn't the problem. I'm using privacy browser. The developer wrote, that it's a Google download bug (see here https://redmine.stoutner.com/issues/915).

**Comment by Ilav1** [comment]
It seems like simple file manager isn't the problem. I'm using privacy browser. The developer wrote, that it's a Google download bug (see here https://redmine.stoutner.com/issues/915).
