### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by Baker0o7** [SimpleMobileTools/Simple-File-Manager#653]
Hi first of all thank you for your hard work and beautiful app , kindly would like folder icon color to be added thanks again.

![Screenshot_20221113-212221_File Manager_1.png](https://user-images.githubusercontent.com/113295927/201538080-49e3b809-f828-4efc-9bb6-6976ea65b96e.png)

**Comment by tibbi** [comment]
that isnt on the roadmap, but some nicer folder thumbnails might come

**Comment by Baker0o7** [comment]
Much thanks
