### ISSUE TITLE
F-Droid: Known Vulnerability

### ISSUE THREAD

**Issue by imsi32** [SimpleMobileTools/Simple-File-Manager#656]
It seems like F-Droid found a vulnerability in v6.14.3. I don't know what it is but you can look at this links that shows Simple File Manager has known vulnerability:
 https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.simplemobiletools.filemanager.pro.yml

https://monitor.f-droid.org/anti-feature/KnownVuln

**Comment by Ilav1** [comment]
I also got a message by F-Droid to uninstall simple file manager because of vulnerability

![Screenshot_20221205_141542_org fdroid fdroid_1](https://user-images.githubusercontent.com/102852954/205647201-653c1729-2ff7-4f9e-9138-3291fd5a5e9e.jpg)

**Comment by tibbi** [comment]
theres no vulnerability, guess some monitoring apps dont like the root access

**Comment by wtrh** [comment]
This seems to be due to the fact that vulnerability information is registered in the F-Droid repository.

I haven't looked into it in detail, but from the last commit to the build metadata (https://gitlab.com/fdroid/fdroiddata/-/commit/b90b2c53e5de4d1e30c5a883eb41faa74ed6c0f7#09f81f62688f23c16756b691f24d11685e9f3694), it seems to be related to https://github.com/SimpleMobileTools/Simple-File-Manager/issues/619.

**Comment by tibbi** [comment]
duplicate of #619

**Comment by voidplayer** [comment]
Is this fixed? is it a false positive?

**Comment by SSUPII** [comment]
> Is this fixed? is it a false positive?

This is a closed issue because it is a duplicate of issue id 619 (not going to mention it again).

**Comment by GameOverFlowChart** [comment]
> theres no vulnerability, guess some monitoring apps dont like the root access

So there is a known vurnerability since Aug 2, and people are told that there is no vurnerability. Great.

**Comment by voidplayer** [comment]
> > Is this fixed? is it a false positive?
> 
> This is a closed issue because it is a duplicate of issue id 619 (not going to mention it again).

Sorry, i see the other issue is opened. I skimmed it and thought it was closed
