### ISSUE TITLE
F-Droid: Found Vulnerability

### ISSUE THREAD

**Issue by Eraph** [SimpleMobileTools/Simple-File-Manager#661]
F-Droid is flagging Simple File Manager for having a known security vulnerability.

https://monitor.f-droid.org/anti-feature/KnownVuln
https://f-droid.org/packages/com.simplemobiletools.filemanager.pro/

I can't see any more information about the vulnerability but maybe that's deliberate, I hope you can figure out what's wrong and have it fixed!

**Comment by tibbi** [comment]
it has been fixed in 6.14.4 already, just needs an app update
