### ISSUE TITLE
F-Droid still showing the vulnerability warning on 6.14.4

### ISSUE THREAD

**Issue by vocux** [SimpleMobileTools/Simple-File-Manager#662]
Hey, I just updated to 6.14.4 but the vulnerability warning persists, it is also still shown on the app info page that the app is vulnerable. Am I the only one? Maybe it's something to do with F-Droid though and it just needs some time to update

**Comment by plegrand1** [comment]
Same for me even after clearing all data from fdroid

**Comment by DaijoubuKun** [comment]
I checked this app in the Google Play Store (https://play.google.com/store/apps/details?id=com.simplemobiletools.filemanager.pro) and it is not showing as having any vulnerability, but I have seen apps get past Google's security scanner before. 

Also, in F-Droid I see new permissions, but I don't know if those are for this version, or any recent version. It would be nice to know in the changelog when new permissions are needed.

**Comment by kizm0** [comment]
> where do you see the warnings?

https://f-droid.org/en/packages/com.simplemobiletools.filemanager.pro/

**Comment by tibbi** [comment]
guess they havent rechecked it

**Comment by gbdomubpkm** [comment]
Hello.
How does this app have vulnerabilities? Is it susceptible to being hacked or having data leaks? F-Droid's warning, which even advises to uninstall the app just installed, is not at all reassuring !! Can you explain the nature of the problem with F-Droid ? ... and if there is no risk, that the warnings do not appear!
I like this app and i don't understand the problem.
Regards

**Comment by tibbi** [comment]
There is nothing dangerous in the app. Guess f-droid just marked the previous version with it and now automatically marks all new versions too, until changed manually.

**Comment by lipici** [comment]
Every version of any app is checked manually by them. Thats what they said on telegram group.

**Comment by tibbi** [comment]
ah no, they definitely arent checking it manually. Anyway, it should be fixed soon as per https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11496#note_1208626843

**Comment by lipici** [comment]
So you are saying anyone can upload anything on f -droid ? Wow. I need to talk with them again to clarify.  On telegram group they told me they verify every version before they uploading.

**Comment by tibbi** [comment]
You seem to be mixing 2 things here. New app uploading and existing app updating.

**Comment by vocux** [comment]
By the way, the warning is now gone.
