### ISSUE TITLE
Decompression not working

### ISSUE THREAD

**Issue by slothtown** [SimpleMobileTools/Simple-File-Manager#665]
Version: 6.14.4 Pro from Fdroid

Decompressing a zip file doesn't work. I get the following error: 

`Error: java.lang.IllegalArgumentException: MALFORMED[1]`

**Comment by tibbi** [comment]
does it happen to every file? Isnt the file password protected or something?

**Comment by slothtown** [comment]
It doesn't happen with every zip file. However, the zip it happens with isn't password protected and can be decompressed with DocumentsUI files app.

-------- Original Message --------

**Comment by tibbi** [comment]
can you send a sample file?

**Comment by slothtown** [comment]
Unfortunately I can only reproduce this issue with one specific zip file, and that file is a personal one I can't share. I will now close this issue as I can't reproduce it with another file, but will reopen it later if I face this problem again with another file. Thanks for your time and the great app anyway!
