### ISSUE TITLE
Feature request for color theme presets

### ISSUE THREAD

**Issue by pintergreg** [SimpleMobileTools/Simple-File-Manager#67]
Color customization is really nice in the latest version, but I think a few built-in theme, first of all the old dark theme would be awsome.
Thanks for considerig this.

**Comment by tibbi** [comment]
Yea its on the roadmap for all apps, Ive created a more generic issue at https://github.com/SimpleMobileTools/General-Discussion/issues/19 . It will contain a light theme, dark theme and maybe some other nice ones.
