### ISSUE TITLE
Grid mode doesn't display file's name

### ISSUE THREAD

**Issue by Ezee1015** [SimpleMobileTools/Simple-File-Manager#670]
Hi. Some time ago I noticed about a problem in the grid (since then i've been using the list mode, that doesn't have this problem) which displays the folders correctly (icon and name) but the files only display the icon (or it's preview) whitout the name of such file (and with a bigger size compare to the folders). I don't know if this is how it's meant to be or if it's a bug. Any information you need, let me know. Thank you very much and greetings

![bug showcase](https://user-images.githubusercontent.com/82286822/211396334-0d415065-3f60-421e-b962-e4c0ac434021.png)
![specification](https://user-images.githubusercontent.com/82286822/211396336-3e958f71-4b9f-407c-837f-a1ac5b557c9c.png)
![configuration](https://user-images.githubusercontent.com/82286822/211396341-9f0a0b0e-d722-4e14-b219-cbb10e7a1cc3.jpg)

**Comment by tibbi** [comment]
well, use the top Menu -> Toggle filename visibility
