### ISSUE TITLE
Unusably slow after upgrade to v6.15.0

### ISSUE THREAD

**Issue by contrapunctus-1** [SimpleMobileTools/Simple-File-Manager#673]
It takes >10s to show files, to update the display when scrolling through files, to display the overflow or sort menu, etc. Frequently, doing these actions displays the ANR dialogue. The speed is not affected by the sorting I select. Subsequently attempting these actions is faster (as fast as pre-update).

Nokia 6.1 running Android 9. Installed from F-Droid.

**Comment by contrapunctus-1** [comment]
It doesn't seem to be affected by the number of files. e.g. I set a folder with just one file as my home, swiped the app away from the recent apps, and opened it again. Sometimes, the file was displayed immediately, but it took many seconds for the bookmarks menu or the sort menu to open. Other times, the file didn't appear until 10 or more seconds.

**Comment by vyeol** [comment]
I too was experiencing performance issues in 6.15.x. General slowness of loading seemed to be exacerbated by the fact that upon opening the app, the focus immediately jumped to the search bar on top, simultaneously triggering the keyboard.

Have downgraded to 6.14.x for now but would like to be able to upgrade.
Would it be possible to not auto-focus the search bar upon opening the app, i.e. having to trigger search manually by tapping the search bar, i.e. only when needed and not autmatically?

**Comment by tibbi** [comment]
focusing has been fixed in 6.15.2 already

**Comment by vyeol** [comment]
Just checked it out and works like a charm. Thank you!

**Comment by contrapunctus-1** [comment]
Seems to be fixed here too. Thanks!
