### ISSUE TITLE
Can't rename track, or change artist 

### ISSUE THREAD

**Issue by Damian96** [SimpleMobileTools/Simple-File-Manager#674]
As shown in the screenshot below after setting a valid artist name for a track, renaming it fails.

The track was originally onnamed 'Like a Stone.mp3'.

![Screenshot_2023-01-14-03-14-32-994_com simplemobiletools musicplayer](https://user-images.githubusercontent.com/19414954/212443698-516e8443-6ac4-4063-b58c-794051c7eb6b.jpg)

**Comment by tibbi** [comment]
it is already reported at the music player repository, thats where it belongs
