### ISSUE TITLE
Editor: Lightgrey foreground on white background

### ISSUE THREAD

**Issue by qwerty287** [SimpleMobileTools/Simple-File-Manager#682]
Using the material you theme, the editor text looks like this:
![Screenshot_20230205-140304](https://user-images.githubusercontent.com/80460567/216820472-141767c9-1d23-4138-8c0c-6b9d9ffdaed7.png)
The contrast is too low, would be better to increase it.

**Comment by tibbi** [comment]
what app and OS version are you using?
