### ISSUE TITLE
When opening a file with an unknown extension, the mime type is empty

### ISSUE THREAD

**Issue by dvmc** [SimpleMobileTools/Simple-File-Manager#689]
When opening a file with an unknown extension, the mime type is empty/null, and not e.g. `application/octet-stream` or `*/*`, leaving me in my case just with Intercept the Intent. When I choose one of the aforementioned mime types there, more apps are presented. Might be related to #489. Here is the intercepted intent for extension `.md`:

```
intent://media/external/file/47861#Intent;scheme=content;type=;S.real_file_path_2=%2Fstorage%2Femulated%2F0%2FNotes%2FSrpska2023Daten.md;end 
------------ 
ACTION: android.intent.action.VIEW 
DATA: content://media/external/file/47861 
MIME: 
URI: intent://media/external/file/47861#Intent;scheme=content;type=;S.real_file_path_2=%2Fstorage%2Femulated%2F0%2FNotes%2FSrpska2023Daten.md;end 
FLAGS: 
none 
EXTRAS: 
1 Class: java.lang.String 
Key: real_file_path_2 
Value: /storage/emulated/0/Notes/Srpska2023Daten.md 

------------ 
MATCHING ACTIVITIES: 
none 
```

**Comment by dvmc** [comment]
It seems that when opening a file with `OPEN_AS_DEFAULT`, an empty mime type is submitted. I'm not too familiar with Android intents, but is this ever useful? My suggestion is deleting line 49 in Activity.kt, that way `OPEN_AS_DEFAULT` would yield the mime type `*/*`. https://github.com/SimpleMobileTools/Simple-File-Manager/blob/67f519fb8988ac5e8f0f88d26c891fc40ee84828/app/src/main/kotlin/com/simplemobiletools/filemanager/pro/extensions/Activity.kt#L48-L55

**Comment by tibbi** [comment]
just long press the given file and use Menu -> Open as

**Comment by dvmc** [comment]
Great! That would also be a workaround for issue billthefarmer/notes#44.

However, this does not work for shortcuts.
