### ISSUE TITLE
Add a button to redirect or open the system files(com.google.android.documentsui) inside the Android/data

### ISSUE THREAD

**Issue by ayu2805** [SimpleMobileTools/Simple-File-Manager#691]
It would be great if there was a button in the Internal Storage>Android>data which would open the system files(com.google.android.documentsui) like this:
![Screenshot_20230309-135627_File_Manager.png](https://user-images.githubusercontent.com/76616749/223963803-9cfc826d-e679-40c0-95f9-92d49df7c05c.png)

**Comment by Ayuan2805** [comment]
> what is the purpose of that?

umm to enter the "data" folder easily

**Comment by Nitrovenom** [comment]
It doesn't work anymore on Android 12 after the October Google Play system update.
