### ISSUE TITLE
Extremely slow after updating

### ISSUE THREAD

**Issue by chocolateimage** [SimpleMobileTools/Simple-File-Manager#693]
Every time I open the app/go into a folder, it takes like 30 seconds to load the folder view, it just shows a indeterminate progress bar at the top. I'm at version 6.15.2. I even tried clearing the cache and it didn't work
I'm on Nokia 1.4 Android 11
The other file manager apps that I have are snappy and don't have these kinds of problems.

**Comment by tibbi** [comment]
what folders does it happen to?

**Comment by chocolateimage** [comment]
every folder except empty ones

**Comment by chocolateimage** [comment]
still happening after 6.15.3: https://youtu.be/I1GkZRbVDoo

**Comment by chocolateimage** [comment]
reinstalled the app (from f-droid), and it's now working
