### ISSUE TITLE
Cannot open PDF from a notification

### ISSUE THREAD

**Issue by Spike-from-NH** [SimpleMobileTools/Simple-File-Manager#694]
With Android 8 and Fennec 60.0.2, I downloaded a PDF (a legislative bill cited at https://mobile.twitter.com/RepThomasMassie/status/1640719571169472519). Got a notification when download was complete, pulled it down from top of screen, and tapped on it. It opened SFM 6.15.2 but Java gave "ENOENT, No such file or directory". (I was able to open SFM from shortcut and open the PDF.)

**Comment by Spike-from-NH** [comment]
"ODF" in title is a typo

**Comment by Spike-from-NH** [comment]
Same error when I tap the Fennec pop-up to open the PDF.

**Comment by tibbi** [comment]
any way to reproduce this reliably by downloading any pdf from some website? If the bug still happens..

**Comment by Spike-from-NH** [comment]
The bug no longer occurs with SFM 6.16.0. I can open the PDF by tapping the Notification of completed download or the browser pop-up.
