### ISSUE TITLE
Add SFTP support

### ISSUE THREAD

**Issue by Ayuan2805** [SimpleMobileTools/Simple-File-Manager#698]
It would be great to add SFTP support like I can host a SFTP server from my device so that i can access the files inside of Internal storage from any remote place with the help of supported browser, File Zilla or any supported application with username and password to read and write in the ftp server.

**Comment by tibbi** [comment]
that isnt on the roadmap as our apps have no internet access

**Comment by Ayuan2805** [comment]
> that isnt on the roadmap as our apps have no internet access

Ooh i see...okay
