### ISSUE TITLE
Screen Overlay Detected

### ISSUE THREAD

**Issue by nicolasdanelon** [SimpleMobileTools/Simple-File-Manager#7]
Hi, after allow access to media, photos and files the app request "Screen Overlay Detected"
I try to enable this in my Samsung S6 Edge but the app doesn't open :(

**Comment by tibbi** [comment]
hello, Ive never had that issue myself. However after googling Ive seen that its not related to this particular app at all, for solutions check for example http://forums.androidcentral.com/android-6-0-marshmallow/626142-screen-overlay-detected-app-permissions-twilight.html
