### ISSUE TITLE
whole-app biometric protection issue

### ISSUE THREAD

**Issue by nicktyke** [SimpleMobileTools/Simple-File-Manager#705]
Hi
I notice you have recently added fingerprint protection for the app. Upon launch once enabled, I have to authenticate. However, if I open another app, leaving the file manager running in the background, when I navigate back I can get back in without having to authenticate again. 

If there's a good reason why not and this is deliberate behaviour, that's fine but in my opinion, it somewhat compromises the file security it is presumably designed to offer.
Version 6.15.3, various devices

**Comment by tibbi** [comment]
ye, that is currently the expected behaviour. The protection is needed only at launching the app, not at every resume.
