### ISSUE TITLE
trashed files now show up 

### ISSUE THREAD

**Issue by kitesi** [SimpleMobileTools/Simple-File-Manager#709]
Due to a recent Android update, when I delete media from my default gallery app, the files aren't deleted and are just renamed to dotfiles (e.g `.trashed-original-name.png`). Is there any way to hide these files without hiding all dotfiles?

I would like to continue using the default gallery app. It also has no setting to change this.

App: Photos, version 5.0.74
Phone: One Plus 7t
Android version: 12

**Comment by tibbi** [comment]
not yet, you cannot do that. It wont be supported this way either
