### ISSUE TITLE
[feature]: supports reading *.java and *.kt format files

### ISSUE THREAD

**Issue by andihasan97** [SimpleMobileTools/Simple-File-Manager#715]
please add to support reading *.java (java file) and *.kt (kotlin file) format files

**Comment by tibbi** [comment]
text files can already be read

**Comment by andihasan97** [comment]
> text files can already be read

yes I know the text reader has been added, but files in .java and .kt format cannot be opened

**Comment by tibbi** [comment]
they can, just open them as text files
