### ISSUE TITLE
Feature Requested

### ISSUE THREAD

**Issue by MayaBi7** [SimpleMobileTools/Simple-File-Manager#718]
Currently I have to click on the internal Storage and Select SD Card..

Please make this if I just click on Internal Storage it's changed to SD card..and sorry for my English...😅
![Screenshot_2023-07-05-10-00-09-615_com simplemobiletools filemanager pro](https://github.com/SimpleMobileTools/Simple-File-Manager/assets/96541364/a6cb29fc-d744-4647-b11d-33f377997b61)

![Screenshot_2023-07-05-09-51-55-458_com simplemobiletools filemanager pro-edit](https://github.com/SimpleMobileTools/Simple-File-Manager/assets/96541364/0add44bd-b39a-460f-9e3c-eaafae0a3e63)

**Comment by tibbi** [comment]
that isnt really on the roadmap
