### ISSUE TITLE
Contextual action bar color

### ISSUE THREAD

**Issue by trubitsyn** [SimpleMobileTools/Simple-File-Manager#72]
On my device (API level 23) its background is black. I think it should have the same color as FAB and status bar.

**Comment by trubitsyn** [comment]
I'll create a PR.

**Comment by trubitsyn** [comment]
Same bug in gallery, could you move the issue to Commons repo?

**Comment by tibbi** [comment]
moved it to General Discussion at https://github.com/SimpleMobileTools/General-Discussion/issues/27 . I disabled reporting issues at commons so things related to all apps are at the General Discussion.
