### ISSUE TITLE
Color settings should be applied to PDF viewer 

### ISSUE THREAD

**Issue by 4rg1l** [SimpleMobileTools/Simple-File-Manager#723]
Hi! Great app. 

The color settings should be applied to the integrated PDF viewer too.

**Comment by tibbi** [comment]
you mean the primary color or what exactly? What app version are you using?

**Comment by 4rg1l** [comment]
> you mean the primary color or what exactly? What app version are you using?

Background and foreground (text) colors mostly, in the document itself. I am using latest release (6.15.4).
