### ISSUE TITLE
Quick multiselect

### ISSUE THREAD

**Issue by smichel17** [SimpleMobileTools/Simple-File-Manager#73]
A feature that is missing in every other file manager is the ability to select multiple items in a list without using "select all". For example, select one item, then choose "Select to", and then another item, and all those in between would be selected.

It is useful for situations like, sharing a bunch of photos from a certain date range. You don't want to share all photos in the directory, but there's a lot to manually scroll through and select each one.

**Comment by tibbi** [comment]
Im implementing the drag selection from the gallery right now, will be added in the next release. A "Select all" will be added too as its still missing.
