### ISSUE TITLE
Storage permission not working correctly

### ISSUE THREAD

**Issue by cd-FileX** [SimpleMobileTools/Simple-File-Manager#736]
(I can not test it with other drives but I think after I somehow not gave the permission to my USB Stick, it has never asked me again and so the drive shown stays empty.)

What also could be the case, is that you have to request access every time again the drive was removed and is being input again.

As there is no option known to me how you could still give access to storages without being asked by the app, I opened this either a bug or enhancement.

Simple solution:
If access to storage is denied, ask again when the storage is being tried to be opened by the user.

**Comment by tibbi** [comment]
sadly USB handling on Android is a mess, there are some things we just have to do. Anyway, some related improvements are reported somewhere else.

**Comment by cd-FileX** [comment]
Amaze handles it correctly so maybe worth a look somewhen

https://github.com/TeamAmaze/AmazeFileManager
