### ISSUE TITLE
Latest version missing in F-Droid

### ISSUE THREAD

**Issue by Hainish** [SimpleMobileTools/Simple-File-Manager#74]
The latest version in F-Droid is 2.2.2 (Added on Apr 27, 2017) as opposed to the Play Store, which has 2.3.0

https://f-droid.org/packages/com.simplemobiletools.filemanager/
https://play.google.com/store/apps/details?id=com.simplemobiletools.filemanager&hl=en

**Comment by tibbi** [comment]
well the release is created at https://github.com/SimpleMobileTools/Simple-File-Manager/releases , F-droid just didnt fetch it and theres not much I can do about it. Hope they will do it soon.
