### ISSUE TITLE
In root, access to the /data/data directory is restricted

### ISSUE THREAD

**Issue by gab12** [SimpleMobileTools/Simple-File-Manager#741]
Hello,

I noticed that the /data/data directory has limited access as root.
It only displays 2 directories: simple_file_manager and google.

It should display the directory of all applications installed on the phone.

![Screenshot_20230829-151615_Gestionnaire de fichiers](https://github.com/SimpleMobileTools/Simple-File-Manager/assets/6320898/1bee9359-3ad8-4ab9-b2b9-b1c87ab88c80)

As an example, here is what the same directory displays under the root-explorer application.

![Screenshot_20230829-151736_Root Explorer](https://github.com/SimpleMobileTools/Simple-File-Manager/assets/6320898/6b839e9d-4eae-4215-9455-9176bf98ac8d)

**Comment by Aga-C** [comment]
It's a duplicate of https://github.com/SimpleMobileTools/Simple-File-Manager/issues/685.

**Comment by gab12** [comment]
Sorry
