### ISSUE TITLE
Copy file paths in clipboard

### ISSUE THREAD

**Issue by 6801318d8d** [SimpleMobileTools/Simple-File-Manager#761]
Hello,

Can we implement a feature that allows to copy file paths in the clipboard?

The browser Fulguris doesn't have a file manager to select the downloads folder. It requires inputing a file path directly.

Best

**Comment by 6801318d8d** [comment]
https://github.com/Slion/Fulguris/issues/563

**Comment by Aga-C** [comment]
Long press the file -> three dots on top bar -> `Copy path to clipboard`.

**Comment by 6801318d8d** [comment]
> Long press the file -> three dots on top bar -> `Copy path to clipboard`.

Yeah I missed that ... by bad
