### ISSUE TITLE
Text editor/viewer should be optional

### ISSUE THREAD

**Issue by etha-net** [SimpleMobileTools/Simple-File-Manager#767]
Currently when another Android app (e.g. Revolut) creates a text file (e.g. a CSV file), the text file automatically opens in Simple File Manager, where the user has no way to just save it to a specific folder. Even with apps like "Save on Device" installed, there is no way to pass the file to that app, or to prevent SFM from handling the file in the first place.

There should be a setting in Simple File Manager that disables the text file viewer/editor.

(Or maybe a more elegant solution would be to offer the text editor as a separate app, so people can install it independently from the file manager.)

**Comment by tibbi** [comment]
if you dont want to use our text editor, just pick some other app for handling it

**Comment by etha-net** [comment]
You are right in theory, and maybe the problem is more with Android itself, but as soon as you have ANY text editor installed, Android will only let you choose from those text editor apps to open text files, and you can no longer choose any other generic file handling apps (like "Save on Device"). So currently, the only solution I know of is not to install any text editors, including "Simple File Manager", unfortunately. Hence I think SFM usability would benefit from the text editor functionality being optional. Maybe I'm not the only one.
