### ISSUE TITLE
Chromecast support

### ISSUE THREAD

**Issue by davidhedlund** [SimpleMobileTools/Simple-File-Manager#776]
Simple File Manger is marked as _Incompatible_ in F-Droid that I tried from a brand new _Chromecast with Google TV (HD)_ device.

**Comment by davidhedlund** [comment]
It would be useful for people to have support for it, so they can install apks from Simple File Manger, instead of having to use Google Play in Chromecast.

**Comment by inson1** [comment]
@davidhedlund SMT apps were sold to ad company. Fork is here https://github.com/FossifyOrg

**Comment by davidhedlund** [comment]
> @davidhedlund SMT apps were sold to ad company. Fork is here https://github.com/FossifyOrg

Dammit. Thank you very much for the information.

* https://github.com/FossifyOrg/File-Manager/issues/55
