### ISSUE TITLE
Root filesystem unavailable when root permissions granted.

### ISSUE THREAD

**Issue by tarakbumba** [SimpleMobileTools/Simple-File-Manager#85]
Thank you for this good app. On my LG-D855 phone with CleanRom 2.5 (based on Marshmallow stock rom), using Magisk, app won't show root folder content when root permissions ( and root enabled in settings) granted.It shows root folder contents without root previlages tough.

**Comment by tibbi** [comment]
Hey, can you shoot me a mail at hello@simplemobiletools.com , so I can send you a test version please? It works fine on my device :p

**Comment by morfikov** [comment]
I also can confirm that after granting root privileges there's nothing in the root folder.
![file](https://user-images.githubusercontent.com/3797768/31056075-70c37130-a6cc-11e7-99e7-c247e88a8e1f.png)

**Comment by morfikov** [comment]
@tibbi  any idea on this bug?

**Comment by tibbi** [comment]
a guy reported a similar issue right after releasing it, his problem was that "awk" package was missing and I couldnt use the required command. I guess that will be your issue too. Root folders could be listed without that too, but its currently not a high enough priority to rewrite it.

**Comment by morfikov** [comment]
That's weird because I have busybox installed and:

```
# adb shell
X1_Max:/ $ su
X1_Max:/ # echo $PATH
/su/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/su/xbin:/system/xbin
X1_Max:/ # which awk
/su/xbin/awk

Should I install it somewhere else?
```

**Comment by tibbi** [comment]
Aha, can you then try this version Im attaching? You will probably see some messages appear as you select the root folder while having Root Access enabled in app settings, whats written on them? Uninstall the current one and allow installing apps from unknown sources at the security settings of your device. Remove the ".zip" appendix from the attachment, its just because github doesnt allow uploading .apk files. Thanks
[app-release.apk.zip](https://github.com/SimpleMobileTools/Simple-File-Manager/files/1347493/app-release.apk.zip)

**Comment by morfikov** [comment]
I did what you asked for, but it looks like there's no messages when I select the root folder. I have root access enabled and removed the precious version of the app.

**Comment by tibbi** [comment]
how about this one? Also what if you disable Root Access, do you see any files there?
[app-release.apk.zip](https://github.com/SimpleMobileTools/Simple-File-Manager/files/1347509/app-release.apk.zip)

**Comment by morfikov** [comment]
When I start the app, now I can see this message: 

check: simple mobile tools

Still no root content. What is the "simple mobile tools?

**Comment by tibbi** [comment]
its just a simple echo to see if the console works at all, and I see the output. How about now? What do you see?
[app-release.apk.zip](https://github.com/SimpleMobileTools/Simple-File-Manager/files/1347528/app-release.apk.zip)

**Comment by morfikov** [comment]
Now it says:

`path:`

**Comment by tibbi** [comment]
Alright, this should do something more then. It apparently somehow got to trimming the slash of the root folder, which is not happening on my device.
[app-release.apk.zip](https://github.com/SimpleMobileTools/Simple-File-Manager/files/1347535/app-release.apk.zip)

**Comment by morfikov** [comment]
Now it's 

`path:/`

**Comment by tibbi** [comment]
and nothing else after it? No files or other messages appear?

**Comment by morfikov** [comment]
No other message, no files.

**Comment by tibbi** [comment]
ok, here is hopefully a last one
[app-release.apk.zip](https://github.com/SimpleMobileTools/Simple-File-Manager/files/1347545/app-release.apk.zip)

**Comment by morfikov** [comment]
It's still the same message and no files.

**Comment by tibbi** [comment]
weird... Ill try a simple "ls", do you see anything?
[app-release.apk.zip](https://github.com/SimpleMobileTools/Simple-File-Manager/files/1347554/app-release.apk.zip)

**Comment by morfikov** [comment]
Wow, now it worked :D

**Comment by tibbi** [comment]
can you send me some screenshot? Maybe the values are in a different order than on my device, so it parses it wrong.

**Comment by morfikov** [comment]
I think it's not what it supposed to be. But at least it displays something :)

**Comment by tibbi** [comment]
tomorrow I will compare it with the output on my device and figure out whats wrong. Thanks for now

**Comment by morfikov** [comment]
Ok. :)

**Comment by tibbi** [comment]
So, how about this one? Ive changed something. You shouldnt see any popups, it should just work in theory.
[app-release.apk.zip](https://github.com/SimpleMobileTools/Simple-File-Manager/files/1350076/app-release.apk.zip)

**Comment by morfikov** [comment]
I've just tested it, and still no files.

**Comment by tibbi** [comment]
oh cmon, how about this one? The first message will be "index <number>", is the number 4 or 5? What about the next messages, can you give me a screenshot of one again? Thanks
[app-release.apk.zip](https://github.com/SimpleMobileTools/Simple-File-Manager/files/1350101/app-release.apk.zip)

**Comment by morfikov** [comment]
Index 5
![screenshot_20171002-213411](https://user-images.githubusercontent.com/3797768/31095538-7d2cf930-a7b9-11e7-8118-bce116f676cb.png)

**Comment by tibbi** [comment]
How about this? It should print out a weird command.
[app-release.apk.zip](https://github.com/SimpleMobileTools/Simple-File-Manager/files/1350143/app-release.apk.zip)

**Comment by morfikov** [comment]
![screenshot_20171002-214657](https://user-images.githubusercontent.com/3797768/31096067-43d1c92a-a7bb-11e7-90e7-00f78a3e7f93.png)

**Comment by tibbi** [comment]
You should see some "Output xxx" messages now, do you? Do you maybe see some "RETURN xxx" or "ERROR xxx"?
[app-release.apk.zip](https://github.com/SimpleMobileTools/Simple-File-Manager/files/1350190/app-release.apk.zip)

**Comment by morfikov** [comment]
No messages this time.

**Comment by tibbi** [comment]
wow, how about now?
[app-release.apk.zip](https://github.com/SimpleMobileTools/Simple-File-Manager/files/1350281/app-release.apk.zip)

**Comment by morfikov** [comment]
Now it says:
Completed 0

**Comment by tibbi** [comment]
ok Ill try removing parts of that command, hope it wont last much longer. Do some messages appear now?
[app-release.apk.zip](https://github.com/SimpleMobileTools/Simple-File-Manager/files/1350356/app-release.apk.zip)

**Comment by morfikov** [comment]
No messages.

**Comment by tibbi** [comment]
now?
[app-release.apk.zip](https://github.com/SimpleMobileTools/Simple-File-Manager/files/1350382/app-release.apk.zip)

**Comment by morfikov** [comment]
Still nothing.

**Comment by tibbi** [comment]
this?
[app-release.apk.zip](https://github.com/SimpleMobileTools/Simple-File-Manager/files/1350412/app-release.apk.zip)

**Comment by morfikov** [comment]
Yes, now I have something.

**Comment by tibbi** [comment]
the file/folder permissions? letters like d/r/w/x/- ?

**Comment by morfikov** [comment]
Yes

**Comment by tibbi** [comment]
now?
[app-release.apk.zip](https://github.com/SimpleMobileTools/Simple-File-Manager/files/1350442/app-release.apk.zip)

**Comment by morfikov** [comment]
No messages.

**Comment by tibbi** [comment]
I dont know man, looks like there is something wrong with the `system` command inside `awk`. Its strange that it doesnt even give some error, I dont know how to fix it without having a broken device. Ill give up now as it apparently doesnt affect anyone else, but thanks a lot for the testing and feedback.

**Comment by morfikov** [comment]
Maybe it's because of Android 7.0?

**Comment by tibbi** [comment]
Im not sure. There just arent enough people using the file manager yet, especially with root access. I will have a rooted xiaomi where I want to install Android 7, I just have to wait 2 more days before they allow unlocking it...

**Comment by morfikov** [comment]
Ok, so if you had something to test, just ask. :)

**Comment by tibbi** [comment]
you could test Amaze File Manager at https://play.google.com/store/apps/details?id=com.amaze.filemanager , or its at f-droid too. Its an opensource file manager, it has root access hidden somewhere inside settings too. Ive checked their code already, but it looks weird. I might have to rewrite my way of handling root folders too so it wont use `awk` at all. The File manager just isnt a priority for now tho, there are more popular apps too.

**Comment by morfikov** [comment]
I just checked it, and it's root feature works fine. BTW: it's really nice app :)

**Comment by tibbi** [comment]
ok thanks. Guess you can use it if you need root :D

**Comment by tibbi** [comment]
Root handling will be rewritten in 3.2.0, check if is better. You still cannot really do any operations, just hopefully browse the items.

**Comment by morfikov** [comment]
I just checked and I don't have good news. When I grant root permissions and select the "root" storage, the app thinks a few seconds and then crash.

**Comment by tibbi** [comment]
Ok, I see your crashdump, it shouldnt be anything difficult. Just to know for sure whats wrong, can you try this version? It shouldnt crash, can you send me the message that will appear? Thanks
[Uploading file-manager-release.apk.zip…]()

**Comment by morfikov** [comment]
Here's the message:
https://i.imgur.com/ACY9Egx.png

**Comment by tibbi** [comment]
alright cool, thanks. Can you try this, if it works? You wont see any error messages in case it goes wrong. Try browsing between folders etc.
[file-manager-release.apk.zip](https://github.com/SimpleMobileTools/Simple-File-Manager/files/1664104/file-manager-release.apk.zip)

**Comment by morfikov** [comment]
It looks like it's working now (at least I get the file list), but files has 0-byte size.
I got 1 crash while switching the dirs.
And also switching dirs takes a really long time, and sometimes the app hangs.

**Comment by tibbi** [comment]
ok thats good enough, I will be improving it over time step by step :) I will update the playstore version in a couple days, i dont want to update it too frequently. Get version 3.2.1 from playstore whenever it gets available so you wont miss the updates. Thanks

**Comment by tibbi** [comment]
Ive just released 3.2.1, it should fix that crash

**Comment by morfikov** [comment]
I had that crash only once, and I wasn't able to reproduce the issue after that.

I just checked whether changing dirs works without a problem, and it does, but it's a little bit slow -- I wasn't able to enter a dir that has 100+ files in it, but there was no crash, so I think it's good. :D

**Comment by tibbi** [comment]
alright. Ye it will be improving over time, step by step :) Root file handling is done in a whole different way than normal files so I basically have to implement it from scratch.

**Comment by pacien** [comment]
Hello, I am encountering a different but related issue with v3.3.2 running on Android 5.1.1.
Please see the attached screenshot.

![screenshot_2018-03-20-20-10-25](https://user-images.githubusercontent.com/1449319/37677447-6299f5a4-2c7b-11e8-9590-95e9995a9c43.png)

**Comment by tibbi** [comment]
heh, ye Ill take a look at it someday, thanks

**Comment by tibbi** [comment]
some rooting related things changed since then, open a new clean issue if some reproducible issues still happen
