### ISSUE TITLE
Sharing with Conversations fails

### ISSUE THREAD

**Issue by contrapunctus-1** [SimpleMobileTools/Simple-File-Manager#86]
To replicate -
1. Long press a file (a PDF, in my case)
2. Overflow menu
3. Share
4a. Select one of the suggestions,
4b. or select Conversations and select a chat
The application switches as though sharing was successful, but no file is actually sent.

**Comment by contrapunctus-1** [comment]
Can't reproduce with Conversations v2.2.5 and SFM v4 🤷
Should I close this?

**Comment by tibbi** [comment]
I guess so, seems like it was an issue on their side then :)
