### ISSUE TITLE
tabs

### ISSUE THREAD

**Issue by redojg** [SimpleMobileTools/Simple-File-Manager#88]
add tabs like in notes app

**Comment by tibbi** [comment]
for folders you mean, so you could swipe left for going back?

**Comment by redojg** [comment]
for folders so you can have multiple folders open to quickly switching them

**Comment by tibbi** [comment]
you can use Favorites for fast switching, swiping left could go a folder up.

**Comment by redojg** [comment]
there is already a back button and path for going up. favorites are not so good for folders you need right now, but wont need after. You need to add folder and than remove it while you could just "delete" by closing(opening should be just swipe)

**Comment by alpenblauwtje** [comment]
Except for file managers on Linux/Windows I personally never felt the need for this on Android. It also might make the interface quite complex.

**Comment by redojg** [comment]
It depend on the usage. Somebody needs it, somebody doesnt need file manager at all. The interface will look almost the same.

**Comment by dl200010** [comment]
This honestly would be a great feature, since many other file managers have it.

**Comment by tibbi** [comment]
it isnt really on the roadmap so Ill close this
