### ISSUE TITLE
[Question] Animation when changing theme

### ISSUE THREAD

**Issue by smichel17** [SimpleMobileTools/Simple-File-Manager#9]
When enabling/disabling the dark theme, there's an animation that makes the process feel much smoother than most apps. I'd like to see if I can put together some PRs to add that animation to some other apps I use. Relevant code (from settingsActivity.java):
```
private void restartActivity() {
    TaskStackBuilder.create(getApplicationContext()).addNextIntentWithParentStack(getIntent()).startActivities();
}
```

Does TaskStackBuilder create the animation, too? I'm relatively new to Android dev and just want to make sure I'm not missing anything.

Thank you!

**Comment by tibbi** [comment]
it does not create the animation, the animation is the default one for launching an activity. I havent added anything special about it at all.

**Comment by smichel17** [comment]
hmm. Most apps I've seen don't include the animation for launching an activity when they recreate it after changing theme. Thanks for the info.

**Comment by tibbi** [comment]
Im not sure how to the other apps do it, looks like they explicitly disable the animation with overridePendingTransition(0, 0);
