### ISSUE TITLE
add delete/move/copy of selected items as icons to main panel (around properties and rename buttons)

### ISSUE THREAD

**Issue by redojg** [SimpleMobileTools/Simple-File-Manager#90]

**Comment by tibbi** [comment]
I want to keep properties and rename as the highest priority there for now, thats what people needed. You can select many items and use batch copy/move/delete so its enough to press it once, but you cannot batch rename, so it has to be easily accessible.

**Comment by redojg** [comment]
i didn't mean to replace them, but put them together. where is lot of free space even in portrait mode

**Comment by tibbi** [comment]
its not me deciding how many buttons are shown. Its a system thing.

**Comment by redojg** [comment]
but thats a part of your app right? so its using a lib  which controls that, so you can edit that?

**Comment by tibbi** [comment]
its a standard built in action bar, I dont want to customize it. It really wouldnt be that easy either.

**Comment by redojg** [comment]
then you could add an optional second bar with action icons, which could be placed at the top(uder action bar) or the bottom of the app

**Comment by redojg** [comment]
Could you comment if second bar will be implemented or not? Should not be difficult and makes usage faster for people who makes many operations on files.

**Comment by tibbi** [comment]
No, i dont plan adding a second bar anytime soon.
