### ISSUE TITLE
Access a file through the category section.

### ISSUE THREAD

**Issue by altaf933** [SimpleMobileTools/Simple-File-Manager#95]
A separate section would have different type  categories (i.e Music, Videos, apk etc) that would easy for the users to target specific files.

**Comment by morfikov** [comment]
Like in the stock app:

![screenshot_20171001-174642](https://user-images.githubusercontent.com/3797768/31056364-b3806b00-a6d0-11e7-9e68-db39baf9bd3b.png)

**Comment by aleex5** [comment]
the application has the categories, but the design is too simple and a bit off, in other applications the design with icons is used as the first thing you see when you open the file manager, so it is more attractive for the users.

**Comment by tibbi** [comment]
it has already been added
