### ISSUE TITLE
Permission Denial: requires android.permission.MANAGE_DOCUMENTS

### ISSUE THREAD

**Issue by morfikov** [SimpleMobileTools/Simple-File-Manager#98]
Extracting ZIP files, copying files or creating new one inside of the external SD card gives the following error:

![screenshot_20171001-175443](https://user-images.githubusercontent.com/3797768/31056448-00fb306c-a6d2-11e7-92f9-429e426fb54a.png)

Here are the granted permissions:
![file2](https://user-images.githubusercontent.com/3797768/31056466-577a9720-a6d2-11e7-88e7-2da505a74908.png)

**Comment by tibbi** [comment]
what Android version do you have? Can you try using "Clear Data" on the app in device settings? Thanks

**Comment by morfikov** [comment]
Android 7.0

It looks like that clearing the data helped:
![file3](https://user-images.githubusercontent.com/3797768/31057984-37ed68dc-a6ec-11e7-9349-0e978822ecc1.png)

**Comment by tibbi** [comment]
You have the File manager installed for quite a while now, right? You aren't a new user?

**Comment by morfikov** [comment]
I've been testing it for just a few days.

**Comment by tibbi** [comment]
Thats weird, you should have gotten the proper SD card path on the first try already. I will check what can be improved there. Thanks

**Comment by morfikov** [comment]
I think I know what was wrong. I probably accidentally selected subfolder of the external SD card instead of its root folder. :)

**Comment by tibbi** [comment]
there is a check which should prevent that, Ive added an extra thing which could help in some cases.
